"""Mock Flask server for testing video upload and transcription jobs."""

import datetime
import os
import threading
import time
import uuid

from flask import Flask, jsonify, request, send_file
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# ─── Error handlers ──────────────────────────────────────────────────────────

@app.errorhandler(404)
def not_found(_error):
    """Return JSON for 404 errors."""
    return jsonify({'error': 'Endpoint not found'}), 404

@app.errorhandler(405)
def method_not_allowed(_error):
    """Return JSON for 405 errors."""
    return jsonify({'error': 'Method not allowed'}), 405

@app.errorhandler(500)
def internal_error(_error):
    """Return JSON for 500 errors."""
    return jsonify({'error': 'Internal server error'}), 500

# ─── Data stores ─────────────────────────────────────────────────────────────

users = {}
videos = []
chunk_storage = {}
jobs = {}

UPLOAD_FOLDER = os.path.join(os.path.dirname(__file__), 'uploads')
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

# ─── Helpers ─────────────────────────────────────────────────────────────────

def utc_now_iso():
    """Return current UTC time in ISO 8601 with milliseconds and 'Z'."""
    return datetime.datetime.now(datetime.UTC).isoformat(
        timespec='milliseconds'
    ).replace('+00:00', 'Z')

def generate_mock_transcript():
    """Return a static sample transcript."""
    return (
        "This is a sample transcript generated by the mock server.\n"
        "It contains multiple sentences that demonstrate the output format.\n"
        "The lecture covers important topics in artificial intelligence and "
        "machine learning.\n"
        "Deep learning models have revolutionized the field of "
        "natural language processing.\n"
        "Transformers, in particular, have become the backbone of "
        "modern AI systems."
    )

def generate_mock_segments():
    """Return a list of mock transcript segments with timestamps."""
    return [
        {
            "text": "This is a sample transcript generated by the mock server.",
            "start": 0.0,
            "end": 5.2,
            "language": "en"
        },
        {
            "text": "It contains multiple sentences that demonstrate "
                    "the output format.",
            "start": 5.2,
            "end": 10.8,
            "language": "en"
        },
        {
            "text": "The lecture covers important topics in artificial "
                    "intelligence and machine learning.",
            "start": 10.8,
            "end": 16.5,
            "language": "en"
        },
        {
            "text": "Deep learning models have revolutionized the field of "
                    "natural language processing.",
            "start": 16.5,
            "end": 22.3,
            "language": "en"
        },
        {
            "text": "Transformers, in particular, have become the backbone of "
                    "modern AI systems.",
            "start": 22.3,
            "end": 28.0,
            "language": "en"
        },
    ]

def process_job(job_id):
    """Simulate background job processing with progress updates."""
    job = jobs.get(job_id)
    if not job:
        return

    progress = 0.0
    while progress < 1.0:
        time.sleep(1)
        progress += 0.1
        if progress > 1.0:
            progress = 1.0
        job['progress'] = progress
        if progress >= 1.0:
            job['status'] = 'completed'
            job['transcript'] = generate_mock_transcript()
            job['segments'] = generate_mock_segments()

# ─── Dummy project ──────────────────────────────────────────────────────────
# You must place a sample.mp4 file in the uploads/ folder for this to work.

dummy_project = {
    'key': 'dummy-key-123',
    'name': 'Sample Video',
    'file_name': 'sample.mp4',
    'uploaded': utc_now_iso(),
    'last_opened': None,
    'duration': 60.0,
    'fps': 30.0,
    'file_size': 10485760,
    'segment_count': 5,
    'languages': ['en', 'de'],
    'thumbnail_url': None,
    'segmentation_done': True,
    'segmentation_progress': 100,
}
videos.append(dummy_project)

# Pre‑register a test user
users['testuser@example.com'] = {
    'name': 'Test User',
    'password': 'YourSecurePassword123'
}

# ─── Auth endpoints ─────────────────────────────────────────────────────────

@app.route('/register', methods=['POST'])
def register():
    """Register a new user."""
    email = request.form.get('email')
    password = request.form.get('password')
    name = request.form.get('name', '')
    if not email or not password:
        return jsonify({'message': 'Email and password required'}), 400
    if email in users:
        return jsonify({'message': 'User already exists'}), 400
    users[email] = {'name': name, 'password': password}
    token = str(uuid.uuid4())
    return jsonify({'token': token, 'message': 'User registered successfully'}), 201

@app.route('/login', methods=['POST'])
def login():
    """Log in an existing user."""
    email = request.form.get('email')
    password = request.form.get('password')
    if not email or not password:
        return jsonify({'message': 'Email and password required'}), 400
    user = users.get(email)
    if not user or user['password'] != password:
        return jsonify({'message': 'Invalid credentials'}), 401
    token = str(uuid.uuid4())
    return jsonify({'token': token, 'message': 'Login successful'}), 200

# ─── Video endpoints ────────────────────────────────────────────────────────

@app.route('/videos', methods=['GET'])
def get_videos():
    """Return the list of uploaded videos."""
    storage_used_gb = sum(v.get('file_size', 0) for v in videos) / (1024.0 ** 3)
    return jsonify({
        'projects': videos,
        'storage_used_gb': round(storage_used_gb, 2),
        'storage_limit_gb': 50.0
    }), 200

@app.route('/video_detail/<video_key>', methods=['GET'])
def video_detail(video_key):
    """Return details for a specific video."""
    for project in videos:
        if project['key'] == video_key:
            detail = project.copy()
            if 'segments' not in detail:
                detail['segments'] = []
            detail['video_url'] = None
            return jsonify(detail), 200
    return jsonify({'error': 'Video not found'}), 404

@app.route('/media/<video_key>')
def serve_video(video_key):
    """Serve the video file for the given key."""
    project = next((p for p in videos if p['key'] == video_key), None)
    if not project:
        return jsonify({'error': 'Video not found'}), 404
    file_name = project.get('file_name')
    if not file_name:
        return jsonify({'error': 'File name not available'}), 404
    file_path = os.path.join(UPLOAD_FOLDER, file_name)
    if not os.path.exists(file_path):
        return jsonify({'error': f'File "{file_name}" not found on disk'}), 404
    return send_file(file_path, as_attachment=False)

@app.route('/upload-chunk', methods=['POST'])
def upload_chunk():
    """Receive a chunk of a file upload."""
    file = request.files.get('file')
    filename = request.form.get('filename')
    chunk_index = int(request.form.get('chunk_index', 0))
    total_chunks = int(request.form.get('total_chunks', 1))
    if not file or not filename:
        return jsonify({'message': 'Missing file or filename'}), 400
    if filename not in chunk_storage:
        chunk_storage[filename] = [None] * total_chunks
    chunk_storage[filename][chunk_index] = file.read()
    return jsonify({'message': 'Chunk uploaded'}), 200

@app.route('/finish-upload', methods=['POST'])
def finish_upload():
    """Complete a chunked upload and persist the file to disk."""
    data = request.get_json()
    filename = data.get('filename')
    auto_segmentation = data.get('auto_segmentation', False)
    if not filename:
        return jsonify({'message': 'Missing filename'}), 400
    chunks = chunk_storage.get(filename)
    if not chunks or any(chunk is None for chunk in chunks):
        return jsonify({'message': 'Incomplete upload'}), 400

    # Combine chunks and write to disk
    combined = b''.join(chunks)
    file_path = os.path.join(UPLOAD_FOLDER, filename)
    with open(file_path, 'wb') as f:
        f.write(combined)
    file_size = len(combined)

    project = {
        'key': str(uuid.uuid4()),
        'name': filename.rsplit('.', 1)[0] if '.' in filename else filename,
        'file_name': filename,
        'uploaded': utc_now_iso(),
        'last_opened': None,
        'duration': 120.0,
        'fps': 30.0,
        'file_size': file_size,
        'segment_count': 0,
        'languages': ['en'],
        'thumbnail_url': None,
        'segmentation_done': auto_segmentation,
        'segmentation_progress': 100 if auto_segmentation else 0,
    }
    videos.append(project)
    del chunk_storage[filename]
    return jsonify({'message': 'Upload finished', 'project': project}), 200

# ─── Job endpoints ──────────────────────────────────────────────────────────

@app.route('/start_job/<video_key>', methods=['POST'])
def start_job(video_key):
    """Start a background transcription job for the given video."""
    data = request.get_json()
    job_id = str(uuid.uuid4())

    job = {
        'id': job_id,
        'video_key': video_key,
        'status': 'processing',
        'progress': 0.0,
        'transcript': None,
        'segments': None,
        'created_at': utc_now_iso(),
        'config': data,
    }
    jobs[job_id] = job
    threading.Thread(target=process_job, args=(job_id,), daemon=True).start()
    return jsonify({'job_id': job_id, 'status': 'processing'}), 200

@app.route('/job_status/<job_id>', methods=['GET'])
def job_status(job_id):
    """Return the current status of a transcription job."""
    job = jobs.get(job_id)
    if not job:
        return jsonify({'error': 'Job not found'}), 404
    return jsonify({
        'status': job['status'],
        'progress': job['progress'],
        'transcript': job.get('transcript'),
        'segments': job.get('segments'),
    }), 200

# ─── Debug endpoints ────────────────────────────────────────────────────────

@app.route('/debug-videos', methods=['GET'])
def debug_videos():
    """Debug: return all video metadata."""
    return jsonify({'count': len(videos), 'projects': videos}), 200

@app.route('/debug-jobs', methods=['GET'])
def debug_jobs():
    """Debug: return all jobs."""
    return jsonify({'count': len(jobs), 'jobs': jobs}), 200

@app.route('/clear-videos', methods=['POST'])
def clear_videos():
    """Clear all uploaded videos (except the dummy one)."""
    videos.clear()
    videos.append(dummy_project)
    chunk_storage.clear()
    return jsonify({'message': 'Cleared'}), 200

if __name__ == '__main__':
    app.run(port=5000, debug=True)
