#!/usr/bin/env python3
"""Merged Flask server combining mock server and upload proxy functionality."""

import base64
import datetime
import io
import json
import logging
import mimetypes
import os
import re
import subprocess
import tempfile
import threading
import time
import uuid
import zipfile

import requests
from flask import Flask, jsonify, request, send_file
from flask_cors import CORS
from docx import Document
from docx.shared import Pt, RGBColor

# BeautifulSoup is imported only when needed for HTML parsing
has_bs4 = False
try:
    from bs4 import BeautifulSoup
    has_bs4 = True
except ImportError:
    logging.warning("BeautifulSoup not installed. Export functions will be limited.")

logging.basicConfig(level=logging.DEBUG)
app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 1024 * 1024 * 1024
app.config["DEBUG"] = True

CORS(
    app,
    origins=[
        "http://localhost:8080",
        "http://127.0.0.1:8080",
        "http://localhost:5000",
        "http://127.0.0.1:5000",
        "*",
    ],
    supports_credentials=True,
    methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_headers=["Content-Type", "Authorization", "X-Forwarded-User", "Accept"],
    expose_headers=["Location", "Content-Disposition"],
)

INTERNAL_SERVER_URL = "https://lt2srv-sscherrer.isl.iar.kit.edu"
TARGET_URL = f"{INTERNAL_SERVER_URL}/upload_lecture"
BASE_URL = INTERNAL_SERVER_URL
UPLOAD_FOLDER = os.path.join(os.path.dirname(__file__), "uploads")
SESSION_FOLDER = os.path.join(os.path.dirname(__file__), "sessions")
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(SESSION_FOLDER, exist_ok=True)

users = {}
videos = []
chunk_storage = {}
jobs = {}
sessions = {}
internal_session = requests.Session()
internal_session.verify = False
_state = {"token": None}


def parse_html_with_bs4(html_content):
    """Parse HTML content using BeautifulSoup if available."""
    if has_bs4 and html_content:
        try:
            soup = BeautifulSoup(html_content, "html.parser")
            return soup
        except (TypeError, ValueError) as e:
            logging.warning("Failed to parse HTML with BeautifulSoup: %s", e)
    return None


def ensure_authenticated(token: str) -> bool:
    """Check if the current session has a valid cookie."""
    if token == _state["token"] and internal_session.cookies:
        try:
            resp = internal_session.get(
                INTERNAL_SERVER_URL, allow_redirects=False, timeout=5
            )
            if resp.status_code == 200 and "dex" not in resp.url:
                return True
        except requests.exceptions.RequestException:
            pass
    headers = {"Authorization": f"Bearer {token}"}
    try:
        resp = internal_session.get(
            INTERNAL_SERVER_URL, headers=headers, allow_redirects=False, timeout=10
        )
        if resp.status_code == 200 and "dex" not in resp.url:
            _state["token"] = token
            return True
        return False
    except requests.exceptions.RequestException:
        return False


def utc_now_iso():
    """Return current UTC time in ISO 8601 with milliseconds and 'Z'."""
    return (
        datetime.datetime.now(datetime.UTC)
        .isoformat(timespec="milliseconds")
        .replace("+00:00", "Z")
    )


def generate_mock_transcript():
    """Return a static sample transcript."""
    return (
        "This is a sample transcript generated by the mock server.\n"
        "It contains multiple sentences that demonstrate the output format.\n"
        "The lecture covers important topics in artificial intelligence "
        "and machine learning.\n"
        "Deep learning models have revolutionized the field of "
        "natural language processing.\n"
        "Transformers, in particular, have become the backbone of "
        "modern AI systems."
    )


def generate_mock_segments():
    """Return a list of mock transcript segments with timestamps."""
    return [
        {
            "text": "This is a sample transcript generated by the mock server.",
            "start": 0.0,
            "end": 5.2,
            "language": "en",
        },
        {
            "text": "It contains multiple sentences that demonstrate "
            "the output format.",
            "start": 5.2,
            "end": 10.8,
            "language": "en",
        },
        {
            "text": "The lecture covers important topics in artificial "
            "intelligence and machine learning.",
            "start": 10.8,
            "end": 16.5,
            "language": "en",
        },
        {
            "text": "Deep learning models have revolutionized the field of "
            "natural language processing.",
            "start": 16.5,
            "end": 22.3,
            "language": "en",
        },
        {
            "text": "Transformers, in particular, have become the backbone of "
            "modern AI systems.",
            "start": 22.3,
            "end": 28.0,
            "language": "en",
        },
    ]


def process_job(job_id):
    """Simulate background job processing with progress updates."""
    job = jobs.get(job_id)
    if not job:
        return
    progress = 0.0
    while progress < 1.0:
        time.sleep(1)
        progress += 0.1
        if progress > 1.0:
            progress = 1.0
        job["progress"] = progress
        if progress >= 1.0:
            job["status"] = "completed"
            job["transcript"] = generate_mock_transcript()
            job["segments"] = generate_mock_segments()


# ─── VIDEO THUMBNAIL GENERATION ────────────────────────────────────────


def generate_video_thumbnail(video_path, thumbnail_path, time_offset=1.0):
    """
    Generate a thumbnail from a video file using ffmpeg.
    Returns True if successful, False otherwise.
    """
    try:
        subprocess.run(["ffmpeg", "-version"], capture_output=True, check=True)

        cmd = [
            "ffmpeg",
            "-i",
            video_path,
            "-ss",
            str(time_offset),
            "-vframes",
            "1",
            "-vf",
            "scale=320:-1",
            "-q:v",
            "2",
            "-y",
            thumbnail_path,
        ]

        result = subprocess.run(
            cmd, capture_output=True, text=True, check=False, timeout=30
        )

        if result.returncode == 0 and os.path.exists(thumbnail_path):
            return True
        else:
            logging.warning("FFmpeg failed: %s", result.stderr)
            return False

    except subprocess.TimeoutExpired:
        logging.warning("FFmpeg timeout generating thumbnail")
        return False
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        logging.warning("FFmpeg error: %s", e)
        return False


def get_video_metadata(video_path):
    """
    Extract video metadata using ffprobe.
    Returns (duration, fps) or (120.0, 30.0) if failed.
    """
    try:
        cmd = [
            "ffprobe",
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_entries",
            "stream=duration,r_frame_rate",
            "-of",
            "json",
            video_path,
        ]

        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=10, check=False
        )
        if result.returncode == 0:
            data = json.loads(result.stdout)
            streams = data.get("streams", [])
            if streams:
                stream = streams[0]
                duration = float(stream.get("duration", 120.0))

                fps_str = stream.get("r_frame_rate", "30/1")
                if "/" in fps_str:
                    num, den = fps_str.split("/")
                    fps = float(num) / float(den) if float(den) > 0 else 30.0
                else:
                    fps = float(fps_str)

                return duration, fps
    except (
        subprocess.SubprocessError,
        FileNotFoundError,
        json.JSONDecodeError,
        TypeError,
        ValueError,
        OSError,
    ) as e:
        logging.warning("Failed to get video metadata: %s", e)

    return 120.0, 30.0


# ─── CURL DOWNLOAD FUNCTIONS ──────────────────────────────────────────


def curl_download(url, output_path, token):
    """
    Download a file using curl with authentication.
    Returns True if successful, False otherwise.
    """
    try:
        cmd = [
            "curl",
            "-s",
            "-L",
            "--insecure",
            "-H",
            f"X-Forward-Auth: {token}",
            "-H",
            f"Authorization: Bearer {token}",
            "-H",
            "User-Agent: Mozilla/5.0 (compatible; LT-Uploader/1.0)",
            "--cookie",
            f"_forward_auth={token}",
            "-o",
            output_path,
            url,
        ]

        subprocess.run(cmd, capture_output=True, text=True, timeout=300, check=False)

        if os.path.exists(output_path) and os.path.getsize(output_path) > 1000:
            return True
        else:
            if os.path.exists(output_path):
                os.remove(output_path)
            return False

    except subprocess.TimeoutExpired as e:
        logging.warning("Curl timeout for %s: %s", url, str(e))
        return False
    except OSError as e:
        logging.warning("Curl error for %s: %s", url, str(e))
        return False


def curl_download_with_headers(url, output_path, token):
    """
    Download a file using curl with additional headers for authentication.
    """
    try:
        cmd = [
            "curl",
            "-s",
            "-L",
            "--insecure",
            "-H",
            f"X-Forward-Auth: {token}",
            "-H",
            f"Authorization: Bearer {token}",
            "-H",
            "Accept: application/json",
            "-H",
            "User-Agent: Mozilla/5.0 (compatible; LT-Uploader/1.0)",
            "--cookie",
            f"_forward_auth={token}",
            "-o",
            output_path,
            url,
        ]

        subprocess.run(cmd, capture_output=True, text=True, timeout=300, check=False)

        if os.path.exists(output_path) and os.path.getsize(output_path) > 1000:
            return True
        else:
            if os.path.exists(output_path):
                os.remove(output_path)
            return False

    except subprocess.TimeoutExpired as e:
        logging.warning("Curl timeout for %s: %s", url, str(e))
        return False
    except OSError as e:
        logging.warning("Curl error for %s: %s", url, str(e))
        return False


def extract_text_from_file(file_path):
    """Extract transcript text from a file."""
    if not os.path.exists(file_path):
        return None

    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
        content = f.read()

    try:
        data = json.loads(content)
        text = extract_text_from_json(data)
        if text:
            return text
    except json.JSONDecodeError:
        pass

    if file_path.endswith((".vtt", ".srt")):
        text = extract_text_from_subtitle(content)
        if text:
            return text

    if content and len(content) > 10:
        return content

    return None


def extract_text_from_json(data):
    """Extract text from JSON data."""
    if isinstance(data, dict):
        for key in ["text", "content", "transcript", "seq"]:
            if key in data and data[key] and isinstance(data[key], str):
                return data[key]

        if "messages" in data and isinstance(data["messages"], list):
            texts = []
            for msg in data["messages"]:
                if isinstance(msg, dict):
                    text = extract_text_from_json(msg)
                    if text:
                        texts.append(text)
            if texts:
                return "\n".join(texts)

        if "data" in data and isinstance(data["data"], list):
            texts = []
            for item in data["data"]:
                text = extract_text_from_json(item)
                if text:
                    texts.append(text)
            if texts:
                return "\n".join(texts)

        for key, value in data.items():
            if isinstance(value, (dict, list)):
                text = extract_text_from_json(value)
                if text:
                    return text

    elif isinstance(data, list):
        texts = []
        for item in data:
            text = extract_text_from_json(item)
            if text:
                texts.append(text)
        if texts:
            return "\n".join(texts)

    return None


def extract_text_from_subtitle(content):
    """Extract text from VTT or SRT subtitle file."""
    lines = content.split("\n")
    text_lines = []
    for line in lines:
        line = line.strip()
        if not line:
            continue
        if "-->" in line:
            continue
        if line.isdigit():
            continue
        if line.startswith("WEBVTT"):
            continue
        if line.startswith("Kind:"):
            continue
        if line.startswith("Language:"):
            continue
        text_lines.append(line)
    return " ".join(text_lines) if text_lines else None


def get_actual_file_url(session_id, filename, html_content=None):
    """
    Determine the correct URL for a file based on its type.
    """
    if html_content:
        if filename == "video.mp4":
            match = re.search(r'<source src="([^"]+)"', html_content)
            if match:
                url = match.group(1)
                if url.startswith("/"):
                    url = f"{INTERNAL_SERVER_URL}{url}"
                return url

        if filename.startswith("subtitles_") and filename.endswith(".vtt"):
            label = filename.replace("subtitles_", "").replace(".vtt", "")
            match = re.search(
                rf'<track label="{label}" kind="subtitles" src="([^"]+)"', html_content
            )
            if match:
                url = match.group(1)
                if url.startswith("/"):
                    url = f"{INTERNAL_SERVER_URL}{url}"
                return url

        if filename.endswith(".wav"):
            match = re.search(r'<source src="([^"]+)"[^>]*type="audio/', html_content)
            if match:
                url = match.group(1)
                if url.startswith("/"):
                    url = f"{INTERNAL_SERVER_URL}{url}"
                return url

    if filename == "messages.json":
        return f"{INTERNAL_SERVER_URL}/archivemediafile/{session_id}/messages.json"

    if filename.endswith(".vtt"):
        label = filename.replace(".vtt", "")
        return f"{INTERNAL_SERVER_URL}/archivemedia/{session_id}/vtt/{label}"

    if filename == "video.mp4":
        return f"{INTERNAL_SERVER_URL}/archivemediafile/{session_id}/video.mp4"

    if filename.endswith(".wav"):
        encoded_name = filename.replace(" ", "%20")
        return f"{INTERNAL_SERVER_URL}/archivemediafile/{session_id}/{encoded_name}"

    encoded_name = filename.replace(" ", "%20")
    return f"{INTERNAL_SERVER_URL}/archivesession/{session_id}/{encoded_name}"


def download_session_files(session_id, token):
    """
    Download all files from a session using curl with correct URLs.
    """
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    os.makedirs(session_dir, exist_ok=True)

    logging.info("=" * 60)
    logging.info("Downloading session %s", session_id)

    html_path = os.path.join(session_dir, "index.html")
    html_url = f"{INTERNAL_SERVER_URL}/archivesession/{session_id}"

    if curl_download(html_url, html_path, token):
        logging.info("Downloaded index.html")
    else:
        logging.warning("Failed to download index.html")
        return False

    html_content = ""
    try:
        with open(html_path, "r", encoding="utf-8") as f:
            html_content = f.read()
    except (OSError, UnicodeDecodeError):
        pass

    video_url = get_actual_file_url(session_id, "video.mp4", html_content)
    video_path = os.path.join(session_dir, "video.mp4")
    if curl_download(video_url, video_path, token):
        logging.info("Downloaded video.mp4")
    else:
        logging.warning("Failed to download video.mp4")

    try:
        track_matches = re.findall(
            r'<track label="([^"]+)" kind="subtitles" src="([^"]+)"', html_content
        )
        for label, src in track_matches:
            if src.startswith("/"):
                src = f"{INTERNAL_SERVER_URL}{src}"
            file_name = f"subtitles_{label}.vtt"
            file_path = os.path.join(session_dir, file_name)
            if curl_download(src, file_path, token):
                logging.info("Downloaded %s", file_name)
    except (OSError, re.error) as e:
        logging.warning("Could not download subtitles: %s", e)

    try:
        audio_match = re.search(r'<source src="([^"]+)"[^>]*type="audio/', html_content)
        if audio_match:
            audio_url = audio_match.group(1)
            if audio_url.startswith("/"):
                audio_url = f"{INTERNAL_SERVER_URL}{audio_url}"
            audio_path = os.path.join(session_dir, "audio.wav")
            if curl_download(audio_url, audio_path, token):
                logging.info("Downloaded audio.wav")
    except (OSError, re.error) as e:
        logging.warning("Could not download audio: %s", e)

    messages_url = f"{INTERNAL_SERVER_URL}/archivemediafile/{session_id}/messages.json"
    messages_path = os.path.join(session_dir, "messages.json")
    if curl_download(messages_url, messages_path, token):
        logging.info(
            "Downloaded messages.json (%d bytes)", os.path.getsize(messages_path)
        )
    else:
        logging.warning("Failed to download messages.json")

    transcripts = extract_transcripts_from_messages(messages_path)
    if transcripts:
        save_transcripts_to_files(session_dir, transcripts)
        logging.info("Extracted %d transcripts from messages.json", len(transcripts))
    else:
        logging.warning("No transcripts extracted from messages.json")

    files = [
        f
        for f in os.listdir(session_dir)
        if os.path.isfile(os.path.join(session_dir, f))
        and os.path.getsize(os.path.join(session_dir, f)) > 1000
    ]

    logging.info("=" * 60)
    logging.info("Session %s: Downloaded %s files total", session_id, len(files))
    for f in files:
        size = os.path.getsize(os.path.join(session_dir, f))
        logging.info("  - %s (%d bytes)", f, size)
    logging.info("=" * 60)

    return len(files) > 0


def extract_transcripts_from_messages(messages_path):
    """Extract transcripts from messages.json file with proper structure handling."""
    if not os.path.exists(messages_path) or os.path.getsize(messages_path) < 100:
        return []

    try:
        with open(messages_path, "r", encoding="utf-8") as f:
            messages_data = json.load(f)

        transcripts = []

        language_map = {}
        numeric_language_map = {}

        if isinstance(messages_data, list):
            for item in messages_data:
                if isinstance(item, list) and len(item) >= 2:
                    lang_id = item[0]
                    msg_str = item[1]
                    try:
                        if isinstance(msg_str, str):
                            msg_data = json.loads(msg_str)
                        elif isinstance(msg_str, dict):
                            msg_data = msg_str
                        else:
                            continue
                    except (json.JSONDecodeError, TypeError):
                        continue

                    if isinstance(msg_data, dict) and "sender" in msg_data:
                        sender = msg_data.get("sender", "")
                        lang_name = extract_language_from_sender(
                            sender, lang_id, numeric_language_map
                        )
                        if lang_id not in numeric_language_map:
                            numeric_language_map[lang_id] = lang_name
                        language_map[sender] = lang_name

        if isinstance(messages_data, list):
            for item in messages_data:
                if isinstance(item, list) and len(item) >= 2:
                    lang_id = item[0]
                    msg_str = item[1]

                    try:
                        if isinstance(msg_str, str):
                            msg_data = json.loads(msg_str)
                        elif isinstance(msg_str, dict):
                            msg_data = msg_str
                        else:
                            continue
                    except (json.JSONDecodeError, TypeError):
                        continue

                    if isinstance(msg_data, dict) and "seq" in msg_data:
                        sender = msg_data.get("sender", "")
                        text = msg_data.get("seq", "").strip()

                        if not text:
                            continue

                        if sender in language_map:
                            lang_name = language_map[sender]
                        elif lang_id in numeric_language_map:
                            lang_name = numeric_language_map[lang_id]
                        else:
                            lang_name = get_language_name_from_sender(sender, lang_id)

                        existing = next(
                            (t for t in transcripts if t.get("language") == lang_name),
                            None,
                        )

                        start_val = msg_data.get("start", 0)
                        end_val = msg_data.get("end", 0)
                        try:
                            start_float = float(start_val) if start_val is not None else 0.0
                        except (ValueError, TypeError):
                            start_float = 0.0
                        try:
                            end_float = float(end_val) if end_val is not None else 0.0
                        except (ValueError, TypeError):
                            end_float = 0.0

                        segment_data = {
                            "text": text,
                            "start": start_float,
                            "end": end_float,
                            "sender": sender,
                            "markup": msg_data.get("markup"),
                            "words": msg_data.get("words"),
                            "word_id": msg_data.get("word_id"),
                        }

                        if existing:
                            existing["text"] += "\n" + text
                            if "segments" not in existing:
                                existing["segments"] = []
                            existing["segments"].append(segment_data)
                        else:
                            transcripts.append(
                                {
                                    "language": lang_name,
                                    "source_file": f"lang_{lang_id}",
                                    "text": text,
                                    "sender": sender,
                                    "segments": [segment_data],
                                }
                            )

        organized_transcripts = organize_transcripts(transcripts)

        return organized_transcripts

    except json.JSONDecodeError as e:
        logging.warning("Could not parse messages.json: %s", e)
    except (OSError, KeyError, TypeError, AttributeError) as e:
        logging.warning("Could not extract transcripts from messages.json: %s", e)

    return []


def extract_language_from_sender(sender, lang_id, numeric_language_map):
    """Extract language name from sender using dynamic mapping."""
    if lang_id in numeric_language_map:
        return numeric_language_map[lang_id]

    if sender.startswith("asr:"):
        num_id = sender.replace("asr:", "")
        if num_id in numeric_language_map:
            return numeric_language_map[num_id]
        return f"Transcript (Original ASR - Language {lang_id})"

    elif sender.startswith("mt:"):
        num_id = sender.replace("mt:", "")
        if num_id in numeric_language_map:
            return f"{numeric_language_map[num_id]} Translation"
        return f"Translation (Language {lang_id})"

    elif sender.startswith("textstructurer:0_"):
        lang_code = sender.replace("textstructurer:0_", "")
        language_names = {
            "en": "English",
            "de": "German",
            "fr": "French",
            "es": "Spanish",
            "it": "Italian",
            "pt": "Portuguese",
            "nl": "Dutch",
            "ru": "Russian",
            "ja": "Japanese",
            "ko": "Korean",
            "zh": "Chinese",
            "ar": "Arabic",
            "hi": "Hindi",
            "pl": "Polish",
            "tr": "Turkish",
            "uk": "Ukrainian",
            "vi": "Vietnamese",
            "th": "Thai",
            "id": "Indonesian",
            "ms": "Malay",
        }
        if lang_code in language_names:
            return f"Transcript (Structured - {language_names[lang_code]})"
        return f"Transcript (Structured - {lang_code})"

    elif sender.startswith("saasr"):
        return f"Transcript (SAASR - Language {lang_id})"

    language_names = {
        "en": "English",
        "de": "German",
        "fr": "French",
        "es": "Spanish",
        "it": "Italian",
        "pt": "Portuguese",
        "nl": "Dutch",
        "ru": "Russian",
        "ja": "Japanese",
        "ko": "Korean",
        "zh": "Chinese",
        "ar": "Arabic",
        "hi": "Hindi",
        "pl": "Polish",
        "tr": "Turkish",
        "uk": "Ukrainian",
        "vi": "Vietnamese",
        "th": "Thai",
        "id": "Indonesian",
        "ms": "Malay",
    }
    for code, name in language_names.items():
        if f"_{code}" in sender or f":{code}" in sender:
            return f"Transcript ({name})"

    return f"Transcript (Language {lang_id})"


def get_language_name_from_sender(sender, lang_id):
    """Get a human-readable language name from sender string (fallback)."""
    if not sender:
        return f"Language {lang_id}"

    language_names = {
        "en": "English",
        "de": "German",
        "fr": "French",
        "es": "Spanish",
        "it": "Italian",
        "pt": "Portuguese",
        "nl": "Dutch",
        "ru": "Russian",
        "ja": "Japanese",
        "ko": "Korean",
        "zh": "Chinese",
        "ar": "Arabic",
        "hi": "Hindi",
        "pl": "Polish",
        "tr": "Turkish",
        "uk": "Ukrainian",
        "vi": "Vietnamese",
        "th": "Thai",
        "id": "Indonesian",
        "ms": "Malay",
    }

    if sender.startswith("asr:"):
        return f"Transcript (Original ASR - Language {lang_id})"
    elif sender.startswith("mt:"):
        return f"Translation (Language {lang_id})"
    elif sender.startswith("textstructurer:0_"):
        lang_code = sender.replace("textstructurer:0_", "")
        if lang_code in language_names:
            return f"Transcript (Structured - {language_names[lang_code]})"
        return f"Transcript (Structured - {lang_code})"
    elif sender.startswith("saasr"):
        return f"Transcript (SAASR - Language {lang_id})"
    else:
        for code, name in language_names.items():
            if f"_{code}" in sender or f":{code}" in sender:
                return f"Transcript ({name})"
        return f"Transcript (Language {lang_id})"


def organize_transcripts(transcripts):
    """Organize transcripts by language, combining related messages."""
    organized = {}

    for t in transcripts:
        lang = t.get("language", "Unknown")
        if lang not in organized:
            organized[lang] = {
                "language": lang,
                "text": "",
                "source_file": t.get("source_file", ""),
                "sender": t.get("sender", ""),
                "segments": [],
                "chapters": [],
                "summaries": [],
                "post_edited": [],
                "notes": [],
            }
        if organized[lang]["text"]:
            organized[lang]["text"] += "\n"
        organized[lang]["text"] += t.get("text", "")

        if "segments" in t:
            organized[lang]["segments"].extend(t.get("segments", []))

    result = list(organized.values())

    def sort_key(item):
        lang = item.get("language", "")
        if "Original" in lang:
            return 0
        elif "Structured" in lang:
            return 1
        elif "Translation" in lang:
            return 2
        else:
            return 3

    result.sort(key=sort_key)

    return result


def save_transcripts_to_files(session_dir, transcripts):
    """Save transcripts to JSON and TXT files."""
    if not transcripts:
        return

    json_path = os.path.join(session_dir, "transcripts.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json_data = []
        for t in transcripts:
            clean_t = {
                "language": t.get("language", "Unknown"),
                "source_file": t.get("source_file", ""),
                "text": t.get("text", ""),
            }
            if "segments" in t:
                clean_t["segments"] = t.get("segments", [])
            json_data.append(clean_t)
        json.dump(json_data, f, ensure_ascii=False, indent=2)
    logging.info("Saved transcripts to %s", json_path)

    txt_path = os.path.join(session_dir, "transcript.txt")
    with open(txt_path, "w", encoding="utf-8") as f:
        for t in transcripts:
            f.write(f"{'=' * 60}\n")
            f.write(f"Language: {t.get('language', 'Unknown')}\n")
            f.write(f"Source: {t.get('source_file', 'N/A')}\n")
            if "sender" in t:
                f.write(f"Sender: {t.get('sender', 'N/A')}\n")
            f.write(f"{'=' * 60}\n")
            f.write(t.get("text", ""))
            f.write("\n\n")
    logging.info("Saved plain text to %s", txt_path)


# ─── HELPER: SAFE FLOAT CONVERSION ────────────────────────────────────


def safe_float(value, default=0.0):
    """Safely convert a value to float, handling strings and None."""
    if value is None:
        return default
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        try:
            return float(value)
        except (ValueError, TypeError):
            return default
    return default


# ─── STRUCTURED EXPORT FUNCTIONS ──────────────────────────────────────


def extract_structured_data_from_session(session_dir, language_filter=None):
    """
    Extract fully structured data from a session including chapters, summaries,
    speaker tags, and post-edited content.
    """
    json_path = os.path.join(session_dir, "transcripts.json")
    if not os.path.exists(json_path):
        return None

    with open(json_path, "r", encoding="utf-8") as f:
        all_transcripts = json.load(f)

    if language_filter:
        transcripts = [t for t in all_transcripts if t.get("language") == language_filter]
    else:
        transcripts = all_transcripts

    # Try to load messages.json for richer structured data
    messages_path = os.path.join(session_dir, "messages.json")
    structured_messages = []
    if os.path.exists(messages_path):
        try:
            with open(messages_path, "r", encoding="utf-8") as f:
                messages_data = json.load(f)
            if isinstance(messages_data, list):
                for item in messages_data:
                    if isinstance(item, list) and len(item) >= 2:
                        try:
                            msg_data = json.loads(item[1]) if isinstance(item[1], str) else item[1]
                            if isinstance(msg_data, dict):
                                structured_messages.append(msg_data)
                        except (json.JSONDecodeError, TypeError):
                            pass
        except (json.JSONDecodeError, TypeError, OSError):
            pass

    # Build structured data
    structured_data = {
        "transcripts": [],
        "chapters": [],
        "summaries": [],
        "speakers": {},
        "post_edited": [],
        "notes": [],
        "global_summaries": [],
    }

    for t in transcripts:
        transcript_entry = {
            "language": t.get("language", "Unknown"),
            "text": t.get("text", ""),
            "segments": t.get("segments", []),
            "sender": t.get("sender", ""),
        }
        structured_data["transcripts"].append(transcript_entry)

    # Extract chapters, summaries, speaker info from structured messages
    for msg in structured_messages:
        markup = msg.get("markup")
        sender = msg.get("sender", "")
        seq = msg.get("seq", "")
        start = safe_float(msg.get("start", 0))
        end = safe_float(msg.get("end", 0))

        if markup == "chapterBreak":
            structured_data["chapters"].append({
                "start": start,
                "end": end,
                "index": len(structured_data["chapters"]),
            })
        elif markup == "heading":
            if structured_data["chapters"]:
                structured_data["chapters"][-1]["heading"] = seq
        elif markup == "summary":
            structured_data["summaries"].append({
                "text": seq,
                "start": start,
                "end": end,
                "sender": sender,
            })
        elif markup == "postedited":
            compression_rate = "90"
            if ':' in sender:
                parts = sender.split(':')
                if len(parts) > 1 and '_' in parts[1]:
                    compression_rate = parts[1].split('_')[0]
            structured_data["post_edited"].append({
                "text": seq,
                "start": start,
                "end": end,
                "compression_rate": compression_rate,
                "sender": sender,
            })
        elif markup == "notes":
            structured_data["notes"].append({
                "text": seq,
                "start": start,
                "end": end,
                "nested_level": msg.get("nested_level", 0),
                "chapter_index": msg.get("chapter_index", 0),
            })
        elif markup == "global_summary":
            structured_data["global_summaries"].append({
                "text": seq,
                "sender": sender,
            })

        # Extract speaker info from refined_sentence_cluster
        if "refined_sentence_cluster" in msg:
            speaker = msg.get("refined_sentence_cluster")
            if speaker:
                if speaker.startswith("unk-"):
                    speaker = f"Anonymous-{speaker.split('-')[1]}"
                structured_data["speakers"][speaker] = {
                    "name": speaker,
                    "last_seen": datetime.datetime.now().isoformat(),
                }

    return structured_data


def export_structured_docx(session_id, session_dir, language_filter=None):
    """
    Export session data as DOCX with full structure including chapters, summaries,
    speaker tags, and post-edited content.
    """
    structured_data = extract_structured_data_from_session(session_dir, language_filter)
    if not structured_data:
        doc = Document()
        doc.add_heading("No structured data available", 1)
        return io.BytesIO()

    doc = Document()

    # Title
    title = f"Session: {session_id}"
    if language_filter:
        title += f" - {language_filter}"
    doc.add_heading(title, 0)

    # Metadata
    doc.add_paragraph(f"Session ID: {session_id}")
    doc.add_paragraph(
        f"Export Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )
    doc.add_paragraph(f"Total Languages: {len(structured_data['transcripts'])}")
    doc.add_paragraph(f"Total Chapters: {len(structured_data['chapters'])}")
    doc.add_paragraph(f"Total Summaries: {len(structured_data['summaries'])}")
    doc.add_paragraph(f"Total Speakers: {len(structured_data['speakers'])}")
    doc.add_paragraph("")

    # ─── SPEAKERS ──────────────────────────────────────────────────────
    if structured_data["speakers"]:
        doc.add_heading("Speakers", level=1)
        for speaker_name in sorted(structured_data["speakers"].keys()):
            p = doc.add_paragraph()
            run = p.add_run("• ")
            run.bold = True
            p.add_run(speaker_name)
        doc.add_paragraph("")

    # ─── CHAPTERS ──────────────────────────────────────────────────────
    if structured_data["chapters"]:
        doc.add_heading("Table of Contents", level=1)
        for i, chapter in enumerate(structured_data["chapters"]):
            p = doc.add_paragraph()
            run = p.add_run(f"Chapter {i + 1}")
            run.bold = True
            if "heading" in chapter:
                p.add_run(f": {chapter['heading']}")
            start = safe_float(chapter.get("start", 0))
            if start > 0:
                p.add_run(f" ({start:.1f}s)")
        doc.add_paragraph("")

    # ─── TRANSCRIPTS WITH STRUCTURE ──────────────────────────────────
    doc.add_heading("Transcripts", level=1)

    for transcript in structured_data["transcripts"]:
        lang = transcript.get("language", "Unknown")
        doc.add_heading(lang, level=2)

        segments = transcript.get("segments", [])
        if segments:
            for seg in segments:
                text = seg.get("text", "")
                start = safe_float(seg.get("start", 0))
                end = safe_float(seg.get("end", 0))
                sender = seg.get("sender", "")
                markup = seg.get("markup", "")

                p = doc.add_paragraph()
                run = p.add_run(f"[{start:.1f}s - {end:.1f}s] ")
                run.italic = True
                run.font.size = Pt(9)

                # Speaker tag
                if sender:
                    spk_run = p.add_run(f"[{sender}] ")
                    spk_run.bold = True
                    spk_run.font.color.rgb = RGBColor(0, 102, 204)

                # Text
                text_run = p.add_run(text)
                text_run.font.size = Pt(11)

                # Markup indicator
                if markup:
                    p.add_run(f" ({markup})").italic = True

        else:
            doc.add_paragraph(transcript.get("text", ""))
        doc.add_paragraph("")

    # ─── SUMMARIES ─────────────────────────────────────────────────────
    if structured_data["summaries"]:
        doc.add_heading("Summaries", level=1)
        for summary in structured_data["summaries"]:
            start = safe_float(summary.get("start", 0))
            p = doc.add_paragraph()
            p.add_run(f"[{start:.1f}s] ").italic = True
            p.add_run(summary.get("text", ""))
            if summary.get("sender"):
                p.add_run(f" ({summary['sender']})").italic = True
        doc.add_paragraph("")

    # ─── POST-EDITED CONTENT ──────────────────────────────────────────
    if structured_data["post_edited"]:
        doc.add_heading("Post-Edited Content", level=1)
        for pe in structured_data["post_edited"]:
            start = safe_float(pe.get("start", 0))
            p = doc.add_paragraph()
            p.add_run(f"[{start:.1f}s] ").italic = True
            rate_run = p.add_run(f"Compression: {pe.get('compression_rate', 'N/A')}% ")
            rate_run.bold = True
            p.add_run(pe.get("text", ""))
        doc.add_paragraph("")

    # ─── GLOBAL SUMMARIES ─────────────────────────────────────────────
    if structured_data["global_summaries"]:
        doc.add_heading("Global Summaries", level=1)
        for gs in structured_data["global_summaries"]:
            p = doc.add_paragraph()
            p.add_run(gs.get("text", ""))
            if gs.get("sender"):
                p.add_run(f" ({gs['sender']})").italic = True
        doc.add_paragraph("")

    # ─── NOTES ─────────────────────────────────────────────────────────
    if structured_data["notes"]:
        doc.add_heading("Notes", level=1)
        for note in structured_data["notes"]:
            start = safe_float(note.get("start", 0))
            p = doc.add_paragraph()
            p.add_run(f"[{start:.1f}s] ").italic = True
            p.add_run(note.get("text", ""))
        doc.add_paragraph("")

    doc_buffer = io.BytesIO()
    doc.save(doc_buffer)
    doc_buffer.seek(0)
    return doc_buffer


def export_structured_rtf(session_id, session_dir, language_filter=None):
    """Export structured data as RTF with rich formatting."""
    structured_data = extract_structured_data_from_session(session_dir, language_filter)
    if not structured_data:
        return io.BytesIO(b"{\\rtf1\\ansi No structured data available.}")

    rtf_parts = [
        r"{\rtf1\ansi\deff0",
        r"{\fonttbl{\f0\fnil\fcharset0 Arial;}}",
        r"\f0\fs24",
        r"\b\fs32 Session: " + session_id + r"\b0\par\par",
    ]

    if language_filter:
        rtf_parts.append(r"\b\fs28 Filter: " + language_filter + r"\b0\par\par")

    rtf_parts.append(
        r"\b\fs28 Export Date: "
        + datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        + r"\b0\par\par"
    )

    # Speakers
    if structured_data["speakers"]:
        rtf_parts.append(r"\b\fs26 Speakers\b0\par")
        for speaker_name in sorted(structured_data["speakers"].keys()):
            escaped = speaker_name.replace("\\", "\\\\")
            rtf_parts.append(r"\bullet " + escaped + r"\par")
        rtf_parts.append(r"\par")

    # Chapters
    if structured_data["chapters"]:
        rtf_parts.append(r"\b\fs26 Table of Contents\b0\par")
        for i, chapter in enumerate(structured_data["chapters"]):
            heading = f"Chapter {i + 1}"
            if "heading" in chapter:
                heading += f": {chapter['heading']}"
            start = safe_float(chapter.get("start", 0))
            if start > 0:
                heading += f" ({start:.1f}s)"
            rtf_parts.append(r"\bullet " + heading.replace("\\", "\\\\") + r"\par")
        rtf_parts.append(r"\par")

    # Transcripts
    rtf_parts.append(r"\b\fs26 Transcripts\b0\par")
    for transcript in structured_data["transcripts"]:
        lang = transcript.get("language", "Unknown")
        rtf_parts.append(r"\b\fs24 " + lang + r"\b0\par")

        segments = transcript.get("segments", [])
        if segments:
            for seg in segments:
                text = seg.get("text", "").replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")
                start = safe_float(seg.get("start", 0))
                end = safe_float(seg.get("end", 0))
                sender = seg.get("sender", "")

                time_str = f"[{start:.1f}s - {end:.1f}s]"
                rtf_parts.append(r"\i " + time_str + r"\i0 ")

                if sender:
                    rtf_parts.append(r"\b " + sender.replace("\\", "\\\\") + r" \b0")

                rtf_parts.append(text + r"\par")
        else:
            text = transcript.get("text", "").replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")
            rtf_parts.append(text + r"\par")
        rtf_parts.append(r"\par")

    # Summaries
    if structured_data["summaries"]:
        rtf_parts.append(r"\b\fs26 Summaries\b0\par")
        for summary in structured_data["summaries"]:
            text = summary.get("text", "").replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")
            start = safe_float(summary.get("start", 0))
            rtf_parts.append(r"\i [" + f"{start:.1f}s]" + r"\i0 " + text + r"\par")
        rtf_parts.append(r"\par")

    # Post-edited
    if structured_data["post_edited"]:
        rtf_parts.append(r"\b\fs26 Post-Edited Content\b0\par")
        for pe in structured_data["post_edited"]:
            text = pe.get("text", "").replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")
            start = safe_float(pe.get("start", 0))
            rate = pe.get("compression_rate", "N/A")
            rtf_parts.append(
                r"\i [" + f"{start:.1f}s]" + r"\i0 "
                + r"\b Compression: " + rate + r"%\b0 " + text + r"\par"
            )
        rtf_parts.append(r"\par")

    # Global summaries
    if structured_data["global_summaries"]:
        rtf_parts.append(r"\b\fs26 Global Summaries\b0\par")
        for gs in structured_data["global_summaries"]:
            text = gs.get("text", "").replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")
            rtf_parts.append(text + r"\par")
        rtf_parts.append(r"\par")

    # Notes
    if structured_data["notes"]:
        rtf_parts.append(r"\b\fs26 Notes\b0\par")
        for note in structured_data["notes"]:
            text = note.get("text", "").replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")
            start = safe_float(note.get("start", 0))
            rtf_parts.append(r"\i [" + f"{start:.1f}s]" + r"\i0 " + text + r"\par")
        rtf_parts.append(r"\par")

    rtf_parts.append("}")

    rtf_string = "".join(rtf_parts)
    return io.BytesIO(rtf_string.encode("utf-8"))


def export_structured_txt(session_id, session_dir, language_filter=None):
    """Export structured data as plain text with clear formatting."""
    structured_data = extract_structured_data_from_session(session_dir, language_filter)
    if not structured_data:
        return io.BytesIO(b"No structured data available.")

    lines = []
    lines.append("=" * 80)
    lines.append(f"SESSION: {session_id}")
    if language_filter:
        lines.append(f"FILTER: {language_filter}")
    lines.append(f"Export Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("=" * 80)
    lines.append("")

    # Speakers
    if structured_data["speakers"]:
        lines.append("SPEAKERS:")
        lines.append("-" * 40)
        for speaker_name in sorted(structured_data["speakers"].keys()):
            lines.append(f"  • {speaker_name}")
        lines.append("")

    # Chapters / TOC
    if structured_data["chapters"]:
        lines.append("TABLE OF CONTENTS:")
        lines.append("-" * 40)
        for i, chapter in enumerate(structured_data["chapters"]):
            heading = f"Chapter {i + 1}"
            if "heading" in chapter:
                heading += f": {chapter['heading']}"
            start = safe_float(chapter.get("start", 0))
            if start > 0:
                heading += f" ({start:.1f}s)"
            lines.append(f"  {i + 1}. {heading}")
        lines.append("")

    # Transcripts
    lines.append("TRANSCRIPTS:")
    lines.append("=" * 80)

    for transcript in structured_data["transcripts"]:
        lang = transcript.get("language", "Unknown")
        lines.append(f"\n--- {lang} ---")
        lines.append("-" * 40)

        segments = transcript.get("segments", [])
        if segments:
            for seg in segments:
                text = seg.get("text", "")
                start = safe_float(seg.get("start", 0))
                end = safe_float(seg.get("end", 0))
                sender = seg.get("sender", "")

                line = f"[{start:.1f}s - {end:.1f}s]"
                if sender:
                    line += f" [{sender}]"
                line += f" {text}"
                lines.append(line)
        else:
            lines.append(transcript.get("text", ""))
        lines.append("")

    # Summaries
    if structured_data["summaries"]:
        lines.append("\nSUMMARIES:")
        lines.append("-" * 40)
        for summary in structured_data["summaries"]:
            start = safe_float(summary.get("start", 0))
            text = summary.get("text", "")
            lines.append(f"[{start:.1f}s] {text}")
        lines.append("")

    # Post-edited
    if structured_data["post_edited"]:
        lines.append("\nPOST-EDITED CONTENT:")
        lines.append("-" * 40)
        for pe in structured_data["post_edited"]:
            start = safe_float(pe.get("start", 0))
            rate = pe.get("compression_rate", "N/A")
            text = pe.get("text", "")
            lines.append(f"[{start:.1f}s] [Compression: {rate}%] {text}")
        lines.append("")

    # Global summaries
    if structured_data["global_summaries"]:
        lines.append("\nGLOBAL SUMMARIES:")
        lines.append("-" * 40)
        for gs in structured_data["global_summaries"]:
            lines.append(gs.get("text", ""))
        lines.append("")

    # Notes
    if structured_data["notes"]:
        lines.append("\nNOTES:")
        lines.append("-" * 40)
        for note in structured_data["notes"]:
            start = safe_float(note.get("start", 0))
            text = note.get("text", "")
            lines.append(f"[{start:.1f}s] {text}")
        lines.append("")

    lines.append("\n" + "=" * 80)
    lines.append("END OF EXPORT")

    return io.BytesIO("\n".join(lines).encode("utf-8"))


def get_available_languages(session_dir):
    """Get list of available languages from transcripts.json."""
    json_path = os.path.join(session_dir, "transcripts.json")
    languages = []

    if os.path.exists(json_path):
        with open(json_path, "r", encoding="utf-8") as f:
            transcripts = json.load(f)
        languages = list(set(t.get("language", "Unknown") for t in transcripts))
        languages.sort()

    return languages


# ─── EXPORT ROUTES ─────────────────────────────────────────────────────


@app.route("/session_export/<session_id>", methods=["GET"])
def session_export(session_id):
    """Export all session data as a formatted DOCX document."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    if not os.path.exists(session_dir):
        return jsonify({"error": "Session not found"}), 404

    language = request.args.get("language")

    try:
        doc_buffer = export_structured_docx(session_id, session_dir, language)
    except ImportError:
        return (
            jsonify(
                {
                    "error": "python-docx not installed. "
                    "Please install: pip install python-docx"
                }
            ),
            500,
        )

    filename = f"session_{session_id}"
    if language:
        clean_lang = language.replace(" ", "_").replace("(", "").replace(")", "")
        filename = f"session_{session_id}_{clean_lang}"

    return send_file(
        doc_buffer,
        mimetype="application/vnd.openxmlformats-officedocument"
                 ".wordprocessingml.document",
        as_attachment=True,
        download_name=f"{filename}.docx",
    )


@app.route("/session_export_rtf/<session_id>", methods=["GET"])
def session_export_rtf(session_id):
    """Export all session data as a structured RTF document."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    if not os.path.exists(session_dir):
        return jsonify({"error": "Session not found"}), 404

    language = request.args.get("language")

    rtf_buffer = export_structured_rtf(session_id, session_dir, language)

    filename = f"session_{session_id}"
    if language:
        clean_lang = language.replace(" ", "_").replace("(", "").replace(")", "")
        filename = f"session_{session_id}_{clean_lang}"

    return send_file(
        rtf_buffer,
        mimetype="text/rtf",
        as_attachment=True,
        download_name=f"{filename}.rtf",
    )


@app.route("/session_export_txt/<session_id>", methods=["GET"])
def session_export_txt(session_id):
    """Export all session data as structured plain text."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    if not os.path.exists(session_dir):
        return jsonify({"error": "Session not found"}), 404

    language = request.args.get("language")

    txt_buffer = export_structured_txt(session_id, session_dir, language)

    filename = f"session_{session_id}"
    if language:
        clean_lang = language.replace(" ", "_").replace("(", "").replace(")", "")
        filename = f"session_{session_id}_{clean_lang}"

    return send_file(
        txt_buffer,
        mimetype="text/plain",
        as_attachment=True,
        download_name=f"{filename}.txt",
    )


@app.route("/session_export_docx/<session_id>", methods=["GET"])
def session_export_docx(session_id):
    """Export session as a structured DOCX file."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    if not os.path.exists(session_dir):
        return jsonify({"error": "Session not found"}), 404

    language = request.args.get("language")

    try:
        doc_buffer = export_structured_docx(session_id, session_dir, language)
    except ImportError:
        return (
            jsonify(
                {
                    "error": "python-docx not installed. "
                    "Please install: pip install python-docx"
                }
            ),
            500,
        )

    filename = f"session_{session_id}"
    if language:
        clean_lang = language.replace(" ", "_").replace("(", "").replace(")", "")
        filename = f"session_{session_id}_{clean_lang}"

    return send_file(
        doc_buffer,
        mimetype="application/vnd.openxmlformats-officedocument"
                 ".wordprocessingml.document",
        as_attachment=True,
        download_name=f"{filename}.docx",
    )


@app.route("/session_export_structured_json/<session_id>", methods=["GET"])
def session_export_structured_json(session_id):
    """Export session as structured JSON with all metadata."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    if not os.path.exists(session_dir):
        return jsonify({"error": "Session not found"}), 404

    language = request.args.get("language")

    structured_data = extract_structured_data_from_session(session_dir, language)
    if not structured_data:
        return jsonify({"error": "No structured data available"}), 404

    return jsonify(structured_data), 200


@app.route("/session_export_all_languages/<session_id>", methods=["GET"])
def session_export_all_languages(session_id):
    """Export all languages as separate files in a ZIP archive."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    if not os.path.exists(session_dir):
        return jsonify({"error": "Session not found"}), 404

    export_format = request.args.get("format", "all").lower()

    languages = get_available_languages(session_dir)
    if not languages:
        return jsonify({"error": "No transcript data found"}), 404

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zipf:
        for lang in languages:
            clean_lang = lang.replace(" ", "_").replace("(", "").replace(")", "")

            formats_to_export = []
            if export_format == "all":
                formats_to_export = ["txt", "rtf", "docx", "json"]
            elif export_format in ["txt", "rtf", "docx", "json"]:
                formats_to_export = [export_format]
            else:
                formats_to_export = ["txt"]

            if "txt" in formats_to_export:
                txt_buffer = export_structured_txt(session_id, session_dir, lang)
                zipf.writestr(f"{clean_lang}.txt", txt_buffer.getvalue())

            if "rtf" in formats_to_export:
                rtf_buffer = export_structured_rtf(session_id, session_dir, lang)
                zipf.writestr(f"{clean_lang}.rtf", rtf_buffer.getvalue())

            if "docx" in formats_to_export:
                try:
                    doc_buffer = export_structured_docx(session_id, session_dir, lang)
                    zipf.writestr(f"{clean_lang}.docx", doc_buffer.getvalue())
                except ImportError:
                    logging.warning("python-docx not installed, skipping DOCX")

            if "json" in formats_to_export:
                structured_data = extract_structured_data_from_session(
                    session_dir, lang
                )
                if structured_data:
                    zipf.writestr(
                        f"{clean_lang}.json",
                        json.dumps(
                            structured_data, ensure_ascii=False, indent=2
                        ).encode("utf-8")
                    )

    zip_buffer.seek(0)

    return send_file(
        zip_buffer,
        mimetype="application/zip",
        as_attachment=True,
        download_name=f"session_{session_id}_all_languages.zip",
    )


@app.route("/session_languages/<session_id>", methods=["GET"])
def session_languages(session_id):
    """Get list of available languages for a session."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    if not os.path.exists(session_dir):
        return jsonify({"error": "Session not found"}), 404

    languages = get_available_languages(session_dir)
    return jsonify({"languages": languages}), 200


@app.route("/session_transcript_json/<session_id>", methods=["GET"])
def session_transcript_json(session_id):
    """Export session transcripts as JSON."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    if not os.path.exists(session_dir):
        return jsonify({"error": "Session not found"}), 404

    json_path = os.path.join(session_dir, "transcripts.json")
    if os.path.exists(json_path):
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        return jsonify(data), 200

    return jsonify({"error": "No transcript data found"}), 404


@app.route("/session_messages_json/<session_id>", methods=["GET"])
def session_messages_json(session_id):
    """Download the raw messages.json file from the session."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    if not os.path.exists(session_dir):
        return jsonify({"error": "Session not found"}), 404

    token = request.headers.get("Authorization", "").replace("Bearer ", "")
    if not token:
        token = request.cookies.get("_forward_auth", "")

    if token:
        local_path = os.path.join(session_dir, "messages.json")
        if not os.path.exists(local_path) or os.path.getsize(local_path) < 1000:
            url = f"{INTERNAL_SERVER_URL}/archivemediafile/{session_id}/messages.json"
            logging.info("Downloading messages.json from %s", url)
            if curl_download(url, local_path, token):
                logging.info("Successfully downloaded messages.json")

    json_path = os.path.join(session_dir, "messages.json")
    if os.path.exists(json_path) and os.path.getsize(json_path) > 1000:
        return send_file(
            json_path,
            as_attachment=True,
            download_name=f"messages_{session_id}.json",
            mimetype="application/json",
        )

    return jsonify({"error": "messages.json not found"}), 404


@app.route("/session_zip/<session_id>", methods=["GET"])
def download_session_zip(session_id):
    """Download all session files as a ZIP archive."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    if not os.path.exists(session_dir):
        return jsonify({"error": "Session not found"}), 404

    token = request.headers.get("Authorization", "").replace("Bearer ", "")
    if not token:
        token = request.cookies.get("_forward_auth", "")

    if token:
        json_path = os.path.join(session_dir, "messages.json")
        if not os.path.exists(json_path) or os.path.getsize(json_path) < 1000:
            url = f"{INTERNAL_SERVER_URL}/archivemediafile/{session_id}/messages.json"
            curl_download(url, json_path, token)

    zip_path = os.path.join(tempfile.gettempdir(), f"session_{session_id}.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
        for root, _, files in os.walk(session_dir):
            for file in files:
                file_path = os.path.join(root, file)
                if os.path.getsize(file_path) > 1000:
                    zipf.write(file_path, os.path.relpath(file_path, session_dir))

    return send_file(
        zip_path,
        as_attachment=True,
        download_name=f"session_{session_id}.zip",
        mimetype="application/zip",
    )


@app.route("/session_download_all/<session_id>", methods=["GET"])
def session_download_all(session_id):
    """Download all files from a session in a single ZIP."""
    token = request.headers.get("Authorization", "").replace("Bearer ", "")
    if not token:
        token = request.cookies.get("_forward_auth", "")

    if token:
        download_session_files(session_id, token)

    return download_session_zip(session_id)


# ─── Auth endpoints ──────────────────────────────────────────────────────


@app.route("/register", methods=["POST"])
def register():
    """Register a new user with email and password."""
    email = request.form.get("email")
    password = request.form.get("password")
    name = request.form.get("name", "")
    if not email or not password:
        return jsonify({"message": "Email and password required"}), 400
    if email in users:
        return jsonify({"message": "User already exists"}), 400
    users[email] = {"name": name, "password": password}
    return (
        jsonify(
            {"token": str(uuid.uuid4()), "message": "User registered successfully"}
        ),
        201,
    )


@app.route("/login", methods=["POST"])
def login():
    """Log in an existing user and return an auth token."""
    email = request.form.get("email")
    password = request.form.get("password")
    if not email or not password:
        return jsonify({"message": "Email and password required"}), 400
    user = users.get(email)
    if not user or user["password"] != password:
        return jsonify({"message": "Invalid credentials"}), 401
    return jsonify({"token": str(uuid.uuid4()), "message": "Login successful"}), 200


# ─── Video endpoints ──────────────────────────────────────────────────────


@app.route("/videos", methods=["GET"])
def get_videos():
    """Return the list of uploaded videos with storage usage info."""
    for video in videos:
        if video.get("thumbnail_url"):
            if video["thumbnail_url"].startswith("/thumbnails/"):
                video["thumbnail_url"] = (
                    f"http://localhost:5000{video['thumbnail_url']}"
                )

    storage_used_gb = sum(v.get("file_size", 0) for v in videos) / (1024.0**3)
    return (
        jsonify(
            {
                "projects": videos,
                "storage_used_gb": round(storage_used_gb, 2),
                "storage_limit_gb": 50.0,
            }
        ),
        200,
    )


@app.route("/video_detail/<video_key>", methods=["GET"])
def video_detail(video_key):
    """Return details for a specific video by its key."""
    for project in videos:
        if project["key"] == video_key:
            detail = project.copy()
            detail["segments"] = detail.get("segments", [])
            detail["video_url"] = None
            return jsonify(detail), 200
    return jsonify({"error": "Video not found"}), 404


@app.route("/media/<video_key>")
def serve_video(video_key):
    """Serve the video file for the given video key."""
    project = next((p for p in videos if p["key"] == video_key), None)
    if not project:
        return jsonify({"error": "Video not found"}), 404
    file_name = project.get("file_name")
    if not file_name:
        return jsonify({"error": "File name not available"}), 404
    file_path = os.path.join(UPLOAD_FOLDER, file_name)
    if not os.path.exists(file_path):
        return jsonify({"error": f'File "{file_name}" not found on disk'}), 404
    return send_file(file_path, as_attachment=False)


@app.route("/thumbnails/<filename>")
def serve_thumbnail(filename):
    """Serve thumbnail images."""
    if ".." in filename or "/" in filename or "\\" in filename:
        return jsonify({"error": "Invalid filename"}), 400

    thumbnail_path = os.path.join(UPLOAD_FOLDER, filename)
    if not os.path.exists(thumbnail_path):
        return jsonify({"error": "Thumbnail not found"}), 404

    return send_file(thumbnail_path, mimetype="image/jpeg")


@app.route("/upload-chunk", methods=["POST"])
def upload_chunk():
    """Receive a chunk of a file upload for chunked uploads."""
    file = request.files.get("file")
    filename = request.form.get("filename")
    chunk_index = int(request.form.get("chunk_index", 0))
    total_chunks = int(request.form.get("total_chunks", 1))
    if not file or not filename:
        return jsonify({"message": "Missing file or filename"}), 400
    if filename not in chunk_storage:
        chunk_storage[filename] = [None] * total_chunks
    chunk_storage[filename][chunk_index] = file.read()
    return jsonify({"message": "Chunk uploaded"}), 200


@app.route("/finish-upload", methods=["POST"])
def finish_upload():
    """Complete a chunked upload and persist the file to disk."""
    data = request.get_json()
    filename = data.get("filename")
    auto_segmentation = data.get("auto_segmentation", False)
    if not filename:
        return jsonify({"message": "Missing filename"}), 400
    chunks = chunk_storage.get(filename)
    if not chunks or any(chunk is None for chunk in chunks):
        return jsonify({"message": "Incomplete upload"}), 400
    combined = b"".join(chunks)
    file_path = os.path.join(UPLOAD_FOLDER, filename)
    with open(file_path, "wb") as f:
        f.write(combined)
    file_size = len(combined)

    thumbnail_filename = f"{os.path.splitext(filename)[0]}_thumb.jpg"
    thumbnail_path = os.path.join(UPLOAD_FOLDER, thumbnail_filename)
    thumbnail_url = None

    if generate_video_thumbnail(file_path, thumbnail_path):
        thumbnail_url = f"/thumbnails/{thumbnail_filename}"
        logging.info("Generated thumbnail: %s", thumbnail_filename)
    else:
        logging.warning("Failed to generate thumbnail for %s", filename)

    duration, fps = get_video_metadata(file_path)

    project = {
        "key": str(uuid.uuid4()),
        "name": filename.rsplit(".", 1)[0] if "." in filename else filename,
        "file_name": filename,
        "uploaded": utc_now_iso(),
        "last_opened": None,
        "duration": duration,
        "fps": fps,
        "file_size": file_size,
        "segment_count": 0,
        "languages": ["en"],
        "thumbnail_url": thumbnail_url,
        "segmentation_done": auto_segmentation,
        "segmentation_progress": 100 if auto_segmentation else 0,
    }
    videos.append(project)
    del chunk_storage[filename]
    return jsonify({"message": "Upload finished", "project": project}), 200


# ─── Job endpoints ──────────────────────────────────────────────────────


@app.route("/start_job/<video_key>", methods=["POST"])
def start_job(video_key):
    """Start a background transcription job for the given video."""
    data = request.get_json()
    job_id = str(uuid.uuid4())
    job = {
        "id": job_id,
        "video_key": video_key,
        "status": "processing",
        "progress": 0.0,
        "transcript": None,
        "segments": None,
        "created_at": utc_now_iso(),
        "config": data,
    }
    jobs[job_id] = job
    threading.Thread(target=process_job, args=(job_id,), daemon=True).start()
    return jsonify({"job_id": job_id, "status": "processing"}), 200


@app.route("/job_status/<job_id>", methods=["GET"])
def job_status(job_id):
    """Return the current status of a transcription job."""
    job = jobs.get(job_id)
    if not job:
        return jsonify({"error": "Job not found"}), 404
    return (
        jsonify(
            {
                "status": job["status"],
                "progress": job["progress"],
                "transcript": job.get("transcript"),
                "segments": job.get("segments"),
            }
        ),
        200,
    )


# ─── Session output endpoints ──────────────────────────────────────────


@app.route("/session_output/<session_id>", methods=["GET"])
def get_session_output(session_id):
    """Get the session output as a JSON response with file URLs."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)

    token = request.headers.get("Authorization", "").replace("Bearer ", "")
    if not token:
        token = request.cookies.get("_forward_auth", "")

    if token:
        logging.info("Downloading session %s from internal server", session_id)
        download_session_files(session_id, token)

    files = []
    if os.path.exists(session_dir):
        for file in os.listdir(session_dir):
            file_path = os.path.join(session_dir, file)
            if os.path.isfile(file_path) and os.path.getsize(file_path) > 1000:
                files.append(
                    {
                        "name": file,
                        "size": os.path.getsize(file_path),
                        "url": f"/session_file/{session_id}/{file}",
                    }
                )

    status = "ready" if files else "processing"
    return (
        jsonify(
            {
                "session_id": session_id,
                "files": files,
                "total_files": len(files),
                "session_url": f"{INTERNAL_SERVER_URL}/archivesession/{session_id}",
                "status": status,
            }
        ),
        200,
    )


@app.route("/session_file/<session_id>/<filename>", methods=["GET"])
def get_session_file(session_id, filename):
    """Download a specific file from the session."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    file_path = os.path.join(session_dir, filename)
    if not os.path.exists(file_path):
        return jsonify({"error": "File not found"}), 404
    return send_file(file_path, as_attachment=True)


# ─── Upload endpoint ────────────────────────────────────────────────────


@app.route("/upload", methods=["POST", "OPTIONS"])
def upload_lecture():
    """Upload a video file to the internal server using streaming."""
    if request.method == "OPTIONS":
        response = jsonify({"message": "OK"})
        response.headers.add("Access-Control-Allow-Origin", "*")
        response.headers.add(
            "Access-Control-Allow-Headers", "Content-Type,Authorization"
        )
        response.headers.add("Access-Control-Allow-Methods", "GET,POST,OPTIONS")
        return response, 200

    token = request.form.get("token", "")
    if not token:
        return jsonify({"error": "Missing token"}), 400
    if "videofile" not in request.files:
        return jsonify({"error": "No video file provided"}), 400

    file_storage = request.files["videofile"]
    if file_storage.filename == "":
        return jsonify({"error": "Empty filename"}), 400

    session_name = request.form.get("name", file_storage.filename)

    local_filename = f"{uuid.uuid4()}_{file_storage.filename}"
    local_path = os.path.join(UPLOAD_FOLDER, local_filename)

    file_storage.save(local_path)
    file_size = os.path.getsize(local_path)
    logging.info("Saved local copy: %s (%d bytes)", local_filename, file_size)

    video_key = str(uuid.uuid4())
    project = {
        "key": video_key,
        "name": session_name,
        "file_name": local_filename,
        "uploaded": utc_now_iso(),
        "last_opened": None,
        "duration": 120.0,
        "fps": 30.0,
        "file_size": file_size,
        "segment_count": 0,
        "languages": request.form.getlist("language") or ["en"],
        "thumbnail_url": None,
        "segmentation_done": False,
        "segmentation_progress": 0,
    }
    videos.append(project)

    data = {}
    for key in request.form.keys():
        if key == "token":
            continue
        values = request.form.getlist(key)
        data[key] = values[0] if len(values) == 1 else values
    if "path" not in data:
        data["path"] = "/home/admin@example.com"

    headers = {
        "X-Forward-Auth": token,
        "Authorization": f"Bearer {token}",
        "User-Agent": "Mozilla/5.0 (compatible; LT-Uploader/1.0)",
    }
    cookies = {"_forward_auth": token}

    try:
        logging.info("Uploading to internal server: %s", TARGET_URL)
        logging.info("Data keys: %s", list(data.keys()))
        logging.info("File size: %d bytes", file_size)

        with open(local_path, "rb") as f:
            boundary = f"----WebKitFormBoundary{uuid.uuid4().hex[:16]}"
            content_type = f"multipart/form-data; boundary={boundary}"

            def generate_multipart():
                for key, value in data.items():
                    if isinstance(value, list):
                        for v in value:
                            yield f"--{boundary}\r\n"
                            yield f'Content-Disposition: form-data; name="{key}"\r\n\r\n'
                            yield f"{v}\r\n"
                    else:
                        yield f"--{boundary}\r\n"
                        yield f'Content-Disposition: form-data; name="{key}"\r\n\r\n'
                        yield f"{value}\r\n"

                filename = file_storage.filename
                mimetype = mimetypes.guess_type(filename)[0] or "video/mp4"
                yield f"--{boundary}\r\n"
                yield f'Content-Disposition: form-data; name="videofile"; filename="{filename}"\r\n'
                yield f"Content-Type: {mimetype}\r\n\r\n"

                chunk_size = 8192
                while True:
                    chunk = f.read(chunk_size)
                    if not chunk:
                        break
                    yield chunk

                yield b"\r\n"
                yield f"--{boundary}--\r\n"

            class MultipartGenerator:
                """Generate multipart form-data payload chunks for file uploads."""

                def __init__(self, generator_func):
                    self.generator = generator_func()
                    self._iter = iter(self.generator)

                def __iter__(self):
                    return self

                def __next__(self):
                    value = next(self._iter)
                    if isinstance(value, str):
                        return value.encode("utf-8")
                    return value

            body_gen = MultipartGenerator(generate_multipart)

            resp = requests.post(
                TARGET_URL,
                data=body_gen,
                headers={**headers, "Content-Type": content_type},
                cookies=cookies,
                timeout=(30, 3600),
                verify=False,
                allow_redirects=True,
            )

        logging.info("Response status: %s", resp.status_code)
        logging.info("Response URL: %s", resp.url)

        final_url = resp.url
        session_id = None

        if "/archivesession/" in final_url:
            session_id = final_url.split("/archivesession/")[-1].split("/")[0]
            logging.info("Extracted session ID from URL: %s", session_id)
        elif "/session/" in final_url:
            session_id = final_url.split("/session/")[-1].split("/")[0]
            logging.info("Extracted session ID from URL: %s", session_id)

        if not session_id and session_name:
            user_email = data.get("path", "/home/admin@example.com")
            user_email = user_email.strip("/").split("/")[-1]
            path = f"/home/{user_email}/{session_name}"
            session_id = base64.b64encode(path.encode()).decode()
            logging.info("Generated session ID: %s", session_id)

        content = resp.text

        if session_id:
            project["session_id"] = session_id
            project["session_url"] = f"{BASE_URL}/archivesession/{session_id}"
            sessions[session_id] = {
                "id": session_id,
                "name": session_name,
                "video_key": video_key,
                "created_at": utc_now_iso(),
                "url": f"{BASE_URL}/archivesession/{session_id}",
            }
            logging.info("Session created: %s", session_id)

            job = {
                "id": session_id,
                "video_key": video_key,
                "status": "processing",
                "progress": 0.0,
                "transcript": None,
                "segments": None,
                "created_at": utc_now_iso(),
                "config": dict(request.form),
            }
            jobs[session_id] = job
            threading.Thread(
                target=process_job, args=(session_id,), daemon=True
            ).start()

        try:
            response_data = json.loads(content)
            if session_id:
                response_data.update(
                    {
                        "session_id": session_id,
                        "video_key": video_key,
                        "session_url": f"{BASE_URL}/archivesession/{session_id}",
                        "output_url": f"/session_output/{session_id}",
                        "download_url": f"/session_zip/{session_id}",
                    }
                )
            return jsonify(response_data), resp.status_code
        except json.JSONDecodeError:
            if session_id:
                return (
                    jsonify(
                        {
                            "status": "success",
                            "session_id": session_id,
                            "video_key": video_key,
                            "session_url": f"{BASE_URL}/archivesession/{session_id}",
                            "output_url": f"/session_output/{session_id}",
                            "download_url": f"/session_zip/{session_id}",
                            "message": "Upload successful!",
                            "response": content[:500],
                        }
                    ),
                    resp.status_code,
                )
            return (
                jsonify(
                    {
                        "status": "error",
                        "message": "No session ID received",
                        "response": content[:1000],
                        "status_code": resp.status_code,
                        "url": resp.url,
                    }
                ),
                500,
            )

    except requests.exceptions.Timeout:
        logging.error("Request timeout")
        return jsonify({"error": "Request timeout - file may be too large"}), 504
    except requests.exceptions.RequestException as e:
        logging.error("Request error: %s", str(e))
        return jsonify({"error": f"Request failed: {str(e)}"}), 500
    except OSError as e:
        logging.error("Upload error: %s", str(e), exc_info=True)
        return jsonify({"error": f"Upload failed: {str(e)}"}), 500


# ─── Proxy endpoints ────────────────────────────────────────────────────


@app.route("/check-session", methods=["GET"])
def check_session():
    """Forward a GET request to check if the session is authenticated."""
    headers = {}
    auth = request.headers.get("Authorization")
    if auth:
        headers["Authorization"] = auth
    forwarded_user = request.headers.get("X-Forwarded-User")
    if forwarded_user:
        headers["X-Forwarded-User"] = forwarded_user
    try:
        resp = requests.get(
            INTERNAL_SERVER_URL,
            headers=headers,
            allow_redirects=False,
            timeout=10,
            verify=False,
        )
        final_url = resp.url if hasattr(resp, "url") else INTERNAL_SERVER_URL
        is_login_page = resp.status_code == 200 and (
            "Log in to dex" in resp.text or "dex-container" in resp.text
        )
        authenticated = not (
            "dex" in final_url or resp.status_code == 302 or is_login_page
        )
        return jsonify({"authenticated": authenticated}), 200
    except requests.exceptions.RequestException:
        return jsonify({"authenticated": False, "error": "Request failed"}), 200


@app.route("/dex/token", methods=["POST"])
def dex_token():
    """Forward token exchange to the internal server's /dex/token endpoint."""
    try:
        headers = {k: v for k, v in request.headers if k.lower() != "host"}
        resp = requests.post(
            f"{INTERNAL_SERVER_URL}/dex/token",
            data=request.get_data(),
            headers=headers,
            allow_redirects=False,
            timeout=30,
            verify=False,
        )
        return (resp.content, resp.status_code, resp.headers.items())
    except requests.exceptions.RequestException as e:
        return jsonify({"error": f"Proxy error: {str(e)}"}), 500


@app.route("/dex/userinfo", methods=["GET"])
def dex_userinfo():
    """Forward userinfo request to the internal server's /dex/userinfo endpoint."""
    try:
        headers = {k: v for k, v in request.headers if k.lower() != "host"}
        resp = requests.get(
            f"{INTERNAL_SERVER_URL}/dex/userinfo",
            headers=headers,
            allow_redirects=False,
            timeout=30,
            verify=False,
        )
        return (resp.content, resp.status_code, resp.headers.items())
    except requests.exceptions.RequestException as e:
        return jsonify({"error": f"Proxy error: {str(e)}"}), 500


# ─── Debug endpoints ────────────────────────────────────────────────────


@app.route("/debug-videos", methods=["GET"])
def debug_videos():
    """Debug endpoint: return all video metadata."""
    return jsonify({"count": len(videos), "projects": videos}), 200


@app.route("/debug-jobs", methods=["GET"])
def debug_jobs():
    """Debug endpoint: return all jobs."""
    return jsonify({"count": len(jobs), "jobs": jobs}), 200


@app.route("/clear-videos", methods=["POST"])
def clear_videos():
    """Clear all uploaded videos (except the dummy one)."""
    for video in videos:
        if video.get("file_name") and video["file_name"] != "sample.mp4":
            file_path = os.path.join(UPLOAD_FOLDER, video["file_name"])
            if os.path.exists(file_path):
                os.remove(file_path)
            thumb_filename = f"{os.path.splitext(video['file_name'])[0]}_thumb.jpg"
            thumb_path = os.path.join(UPLOAD_FOLDER, thumb_filename)
            if os.path.exists(thumb_path):
                os.remove(thumb_path)
    videos.clear()
    dummy_with_thumb = dummy_project.copy()
    dummy_with_thumb["thumbnail_url"] = None
    videos.append(dummy_with_thumb)
    chunk_storage.clear()
    jobs.clear()
    return jsonify({"message": "Cleared"}), 200


# ─── Dummy project with thumbnail ──────────────────────────────────────

dummy_project = {
    "key": "dummy-key-123",
    "name": "Sample Video",
    "file_name": "sample.mp4",
    "uploaded": utc_now_iso(),
    "last_opened": None,
    "duration": 60.0,
    "fps": 30.0,
    "file_size": 10485760,
    "segment_count": 5,
    "languages": ["en", "de"],
    "thumbnail_url": None,
    "segmentation_done": True,
    "segmentation_progress": 100,
}
videos.append(dummy_project)

users["testuser@example.com"] = {
    "name": "Test User",
    "password": "YourSecurePassword123",
}


if __name__ == "__main__":
    try:
        import urllib3
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
    except ImportError:
        pass
    logging.info("Starting merged server on http://localhost:5000")
    app.run(host="0.0.0.0", port=5000, debug=True)
