#!/usr/bin/env python3
"""Merged Flask server combining mock server and upload proxy functionality."""

import base64
import datetime
import json
import logging
import os
import re
import tempfile
import threading
import time
import uuid
import zipfile

import requests
from flask import Flask, jsonify, request, send_file
from flask_cors import CORS

logging.basicConfig(level=logging.DEBUG)
app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 1024 * 1024 * 1024
app.config["DEBUG"] = True

CORS(
    app,
    origins=[
        "http://localhost:8080",
        "http://127.0.0.1:8080",
        "http://localhost:5000",
        "http://127.0.0.1:5000",
        "*",
    ],
    supports_credentials=True,
    methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_headers=["Content-Type", "Authorization", "X-Forwarded-User", "Accept"],
    expose_headers=["Location", "Content-Disposition"],
)

# ─── Configuration ─────────────────────────────────────────────────────────
INTERNAL_SERVER_URL = "https://lt2srv-sscherrer.isl.iar.kit.edu"
TARGET_URL = f"{INTERNAL_SERVER_URL}/upload_lecture"
BASE_URL = INTERNAL_SERVER_URL
UPLOAD_FOLDER = os.path.join(os.path.dirname(__file__), "uploads")
SESSION_FOLDER = os.path.join(os.path.dirname(__file__), "sessions")
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(SESSION_FOLDER, exist_ok=True)

# ─── Data stores ──────────────────────────────────────────────────────────
users = {}
videos = []
chunk_storage = {}
jobs = {}
sessions = {}
internal_session = requests.Session()
internal_session.verify = False
_state = {"token": None}


def ensure_authenticated(token: str) -> bool:
    """Check if the current session has a valid cookie."""
    if token == _state["token"] and internal_session.cookies:
        try:
            resp = internal_session.get(
                INTERNAL_SERVER_URL, allow_redirects=False, timeout=5
            )
            if resp.status_code == 200 and "dex" not in resp.url:
                return True
        except requests.exceptions.RequestException:
            pass
    headers = {"Authorization": f"Bearer {token}"}
    try:
        resp = internal_session.get(
            INTERNAL_SERVER_URL, headers=headers, allow_redirects=False, timeout=10
        )
        if resp.status_code == 200 and "dex" not in resp.url:
            _state["token"] = token
            return True
        return False
    except requests.exceptions.RequestException:
        return False


def utc_now_iso():
    """Return current UTC time in ISO 8601 with milliseconds and 'Z'."""
    return (
        datetime.datetime.now(datetime.UTC)
        .isoformat(timespec="milliseconds")
        .replace("+00:00", "Z")
    )


def generate_mock_transcript():
    """Return a static sample transcript."""
    return (
        "This is a sample transcript generated by the mock server.\n"
        "It contains multiple sentences that demonstrate the output format.\n"
        "The lecture covers important topics in artificial intelligence "
        "and machine learning.\n"
        "Deep learning models have revolutionized the field of "
        "natural language processing.\n"
        "Transformers, in particular, have become the backbone of "
        "modern AI systems."
    )


def generate_mock_segments():
    """Return a list of mock transcript segments with timestamps."""
    return [
        {
            "text": "This is a sample transcript generated by the mock server.",
            "start": 0.0,
            "end": 5.2,
            "language": "en"
        },
        {
            "text": "It contains multiple sentences that demonstrate "
            "the output format.",
            "start": 5.2,
            "end": 10.8,
            "language": "en"
        },
        {
            "text": "The lecture covers important topics in artificial "
            "intelligence and machine learning.",
            "start": 10.8,
            "end": 16.5,
            "language": "en"
        },
        {
            "text": "Deep learning models have revolutionized the field of "
            "natural language processing.",
            "start": 16.5,
            "end": 22.3,
            "language": "en"
        },
        {
            "text": "Transformers, in particular, have become the backbone of "
            "modern AI systems.",
            "start": 22.3,
            "end": 28.0,
            "language": "en"
        },
    ]


def process_job(job_id):
    """Simulate background job processing with progress updates."""
    job = jobs.get(job_id)
    if not job:
        return
    progress = 0.0
    while progress < 1.0:
        time.sleep(1)
        progress += 0.1
        if progress > 1.0:
            progress = 1.0
        job["progress"] = progress
        if progress >= 1.0:
            job["status"] = "completed"
            job["transcript"] = generate_mock_transcript()
            job["segments"] = generate_mock_segments()


# ─── Dummy data ───────────────────────────────────────────────────────────
dummy_project = {
    "key": "dummy-key-123",
    "name": "Sample Video",
    "file_name": "sample.mp4",
    "uploaded": utc_now_iso(),
    "last_opened": None,
    "duration": 60.0,
    "fps": 30.0,
    "file_size": 10485760,
    "segment_count": 5,
    "languages": ["en", "de"],
    "thumbnail_url": None,
    "segmentation_done": True,
    "segmentation_progress": 100,
}
videos.append(dummy_project)

users["testuser@example.com"] = {
    "name": "Test User",
    "password": "YourSecurePassword123"
}


def download_session_files(session_id, token):
    """Download ALL files from a session using requests."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    os.makedirs(session_dir, exist_ok=True)
    headers = {
        "X-Forward-Auth": token,
        "Authorization": f"Bearer {token}",
        "User-Agent": "Mozilla/5.0 (compatible; LT-Uploader/1.0)",
    }
    cookies = {"_forward_auth": token}
    base_url = f"{INTERNAL_SERVER_URL}/archivesession/{session_id}"
    downloaded = 0
    downloaded_files = set()

    try:
        # ─── 1. GET THE MAIN HTML PAGE ──────────────────────────────
        resp = requests.get(
            base_url, headers=headers, cookies=cookies,
            verify=False, allow_redirects=True, timeout=30
        )
        if resp.status_code != 200:
            logging.error("Failed to get session page: %s", resp.status_code)
            return False

        html_content = resp.text
        html_path = os.path.join(session_dir, "index.html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        downloaded += 1
        logging.info("Downloaded index.html")

        # ─── 2. EXTRACT SESSION MEDIA URLS FROM HTML ──────────────
        # Find the video source URL
        video_src_match = re.search(r'<source src="([^"]+)"[^>]*>', html_content)
        if video_src_match:
            video_url = video_src_match.group(1)
            if video_url.startswith("/"):
                video_url = f"{INTERNAL_SERVER_URL}{video_url}"
            try:
                video_resp = requests.get(
                    video_url, headers=headers, cookies=cookies,
                    verify=False, timeout=120
                )
                if video_resp.status_code == 200 and len(video_resp.content) > 0:
                    with open(os.path.join(session_dir, "video.mp4"), "wb") as f:
                        f.write(video_resp.content)
                    downloaded_files.add("video.mp4")
                    downloaded += 1
                    logging.info("Downloaded video.mp4 (%d bytes)", len(video_resp.content))
            except requests.exceptions.RequestException as e:
                logging.warning("Could not download video: %s", e)

        # Find subtitle tracks
        track_matches = re.findall(
            r'<track label="([^"]+)" kind="subtitles" src="([^"]+)"',
            html_content
        )
        for label, src in track_matches:
            if src.startswith("/"):
                src = f"{INTERNAL_SERVER_URL}{src}"
            try:
                track_resp = requests.get(
                    src, headers=headers, cookies=cookies,
                    verify=False, timeout=30
                )
                if track_resp.status_code == 200 and len(track_resp.content) > 0:
                    filename = f"subtitles_{label}.vtt"
                    with open(os.path.join(session_dir, filename), "wb") as f:
                        f.write(track_resp.content)
                    downloaded_files.add(filename)
                    downloaded += 1
                    logging.info("Downloaded %s (%d bytes)", filename, len(track_resp.content))
            except requests.exceptions.RequestException as e:
                logging.warning("Could not download subtitle %s: %s", label, e)

        # Find audio sources
        audio_matches = re.findall(
            r'<source src="([^"]+)"[^>]*type="audio/', html_content
        )
        for src in audio_matches:
            if src.startswith("/"):
                src = f"{INTERNAL_SERVER_URL}{src}"
            try:
                audio_resp = requests.get(
                    src, headers=headers, cookies=cookies,
                    verify=False, timeout=60
                )
                if audio_resp.status_code == 200 and len(audio_resp.content) > 0:
                    with open(os.path.join(session_dir, "audio.wav"), "wb") as f:
                        f.write(audio_resp.content)
                    downloaded_files.add("audio.wav")
                    downloaded += 1
                    logging.info("Downloaded audio.wav (%d bytes)", len(audio_resp.content))
            except requests.exceptions.RequestException as e:
                logging.warning("Could not download audio: %s", e)

        # ─── 3. TRY ALL POSSIBLE FILE PATTERNS ──────────────────────
        # All possible file types and extensions
        file_types = [
            "transcript", "summary", "notes", "slides", "media",
            "subtitles", "chapters", "metadata", "session", "output",
            "text", "document", "lecture", "recording", "video", "audio"
        ]
        extensions = [".rtf", ".doc", ".docx", ".pdf", ".txt", ".json",
                      ".html", ".xml", ".csv", ".xls", ".xlsx", ".ppt",
                      ".pptx", ".vtt", ".srt", ".mp4", ".webm", ".wav",
                      ".mp3", ".flac", ".ogg", ".zip", ".tar", ".gz"]

        # Try all combinations
        for file_type in file_types:
            for ext in extensions:
                filename = f"{file_type}{ext}"
                if filename in downloaded_files:
                    continue
                try:
                    url = f"{base_url}/{filename}"
                    file_resp = requests.get(
                        url, headers=headers, cookies=cookies,
                        verify=False, timeout=30
                    )
                    if file_resp.status_code == 200 and len(file_resp.content) > 0:
                        file_path = os.path.join(session_dir, filename)
                        with open(file_path, "wb") as f:
                            f.write(file_resp.content)
                        downloaded_files.add(filename)
                        downloaded += 1
                        logging.info("Downloaded %s (%d bytes)", filename, len(file_resp.content))
                except requests.exceptions.RequestException:
                    pass

        # ─── 4. TRY WITH LANGUAGE SUFFIXES ──────────────────────────
        languages = ["en", "de", "fr", "es", "it", "ja", "ko", "zh", "ru", "ar"]
        for lang in languages:
            for file_type in ["transcript", "summary", "notes", "subtitles"]:
                for ext in [".rtf", ".doc", ".docx", ".pdf", ".txt", ".json", ".html", ".vtt", ".srt"]:
                    filename = f"{file_type}_{lang}{ext}"
                    if filename in downloaded_files:
                        continue
                    try:
                        url = f"{base_url}/{filename}"
                        file_resp = requests.get(
                            url, headers=headers, cookies=cookies,
                            verify=False, timeout=30
                        )
                        if file_resp.status_code == 200 and len(file_resp.content) > 0:
                            file_path = os.path.join(session_dir, filename)
                            with open(file_path, "wb") as f:
                                f.write(file_resp.content)
                            downloaded_files.add(filename)
                            downloaded += 1
                            logging.info("Downloaded %s (%d bytes)", filename, len(file_resp.content))
                    except requests.exceptions.RequestException:
                        pass

        # ─── 5. TRY COMMON ENDPOINTS ────────────────────────────────
        endpoints = [
            "/transcript", "/summary", "/notes", "/slides",
            "/vtt", "/media", "/files", "/download", "/export",
            "/text", "/document", "/output", "/data"
        ]
        for endpoint in endpoints:
            for ext in extensions:
                filename = f"{endpoint.strip('/')}{ext}"
                if filename in downloaded_files:
                    continue
                try:
                    url = f"{base_url}{endpoint}{ext}"
                    file_resp = requests.get(
                        url, headers=headers, cookies=cookies,
                        verify=False, timeout=30
                    )
                    if file_resp.status_code == 200 and len(file_resp.content) > 0:
                        file_path = os.path.join(session_dir, filename)
                        with open(file_path, "wb") as f:
                            f.write(file_resp.content)
                        downloaded_files.add(filename)
                        downloaded += 1
                        logging.info("Downloaded %s (%d bytes)", filename, len(file_resp.content))
                except requests.exceptions.RequestException:
                    pass

        # ─── 6. TRY MEDIA WITH DIFFERENT EXTENSIONS ────────────────
        media_extensions = [".mp4", ".webm", ".wav", ".mp3", ".vtt", ".srt", ".rtf", ".doc", ".pdf"]
        for ext in media_extensions:
            filename = f"media{ext}"
            if filename in downloaded_files:
                continue
            try:
                url = f"{base_url}/media{ext}"
                file_resp = requests.get(
                    url, headers=headers, cookies=cookies,
                    verify=False, timeout=30
                )
                if file_resp.status_code == 200 and len(file_resp.content) > 0:
                    file_path = os.path.join(session_dir, filename)
                    with open(file_path, "wb") as f:
                        f.write(file_resp.content)
                    downloaded_files.add(filename)
                    downloaded += 1
                    logging.info("Downloaded %s (%d bytes)", filename, len(file_resp.content))
            except requests.exceptions.RequestException:
                pass

        # ─── 7. TRY TO GET FILES FROM THE HTML PAGE LINKS ──────────
        # Find all links in the HTML that might point to files
        link_matches = re.findall(r'href="([^"]+)"', html_content)
        for link in link_matches:
            # Skip common web resources
            if any(link.endswith(x) for x in ['.css', '.js', '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico']):
                continue
            if link.startswith('/') and not link.startswith('//'):
                full_url = f"{INTERNAL_SERVER_URL}{link}"
            elif link.startswith('http'):
                full_url = link
            else:
                continue

            filename = link.split('/')[-1]
            if not filename or '.' not in filename or filename in downloaded_files:
                continue

            try:
                file_resp = requests.get(
                    full_url, headers=headers, cookies=cookies,
                    verify=False, timeout=30
                )
                if file_resp.status_code == 200 and len(file_resp.content) > 0:
                    file_path = os.path.join(session_dir, filename)
                    with open(file_path, "wb") as f:
                        f.write(file_resp.content)
                    downloaded_files.add(filename)
                    downloaded += 1
                    logging.info("Downloaded %s (%d bytes)", filename, len(file_resp.content))
            except requests.exceptions.RequestException:
                pass

        # ─── 8. SUMMARY ──────────────────────────────────────────────
        files = os.listdir(session_dir)
        logging.info("Session %s: Downloaded %s files total", session_id, len(files))
        logging.info("Files: %s", files)

        return len(files) > 0

    except requests.exceptions.RequestException as e:
        logging.error("Error downloading session %s: %s", session_id, e)
        return False


# ─── Auth endpoints ──────────────────────────────────────────────────────
@app.route("/register", methods=["POST"])
def register():
    """Register a new user with email and password."""
    email = request.form.get("email")
    password = request.form.get("password")
    name = request.form.get("name", "")
    if not email or not password:
        return jsonify({"message": "Email and password required"}), 400
    if email in users:
        return jsonify({"message": "User already exists"}), 400
    users[email] = {"name": name, "password": password}
    return (
        jsonify({"token": str(uuid.uuid4()), "message": "User registered successfully"}),
        201,
    )


@app.route("/login", methods=["POST"])
def login():
    """Log in an existing user and return an auth token."""
    email = request.form.get("email")
    password = request.form.get("password")
    if not email or not password:
        return jsonify({"message": "Email and password required"}), 400
    user = users.get(email)
    if not user or user["password"] != password:
        return jsonify({"message": "Invalid credentials"}), 401
    return jsonify({"token": str(uuid.uuid4()), "message": "Login successful"}), 200


# ─── Video endpoints ──────────────────────────────────────────────────────
@app.route("/videos", methods=["GET"])
def get_videos():
    """Return the list of uploaded videos with storage usage info."""
    storage_used_gb = sum(v.get("file_size", 0) for v in videos) / (1024.0**3)
    return (
        jsonify({
            "projects": videos,
            "storage_used_gb": round(storage_used_gb, 2),
            "storage_limit_gb": 50.0,
        }),
        200,
    )


@app.route("/video_detail/<video_key>", methods=["GET"])
def video_detail(video_key):
    """Return details for a specific video by its key."""
    for project in videos:
        if project["key"] == video_key:
            detail = project.copy()
            detail["segments"] = detail.get("segments", [])
            detail["video_url"] = None
            return jsonify(detail), 200
    return jsonify({"error": "Video not found"}), 404


@app.route("/media/<video_key>")
def serve_video(video_key):
    """Serve the video file for the given video key."""
    project = next((p for p in videos if p["key"] == video_key), None)
    if not project:
        return jsonify({"error": "Video not found"}), 404
    file_name = project.get("file_name")
    if not file_name:
        return jsonify({"error": "File name not available"}), 404
    file_path = os.path.join(UPLOAD_FOLDER, file_name)
    if not os.path.exists(file_path):
        return jsonify({"error": f'File "{file_name}" not found on disk'}), 404
    return send_file(file_path, as_attachment=False)


@app.route("/upload-chunk", methods=["POST"])
def upload_chunk():
    """Receive a chunk of a file upload for chunked uploads."""
    file = request.files.get("file")
    filename = request.form.get("filename")
    chunk_index = int(request.form.get("chunk_index", 0))
    total_chunks = int(request.form.get("total_chunks", 1))
    if not file or not filename:
        return jsonify({"message": "Missing file or filename"}), 400
    if filename not in chunk_storage:
        chunk_storage[filename] = [None] * total_chunks
    chunk_storage[filename][chunk_index] = file.read()
    return jsonify({"message": "Chunk uploaded"}), 200


@app.route("/finish-upload", methods=["POST"])
def finish_upload():
    """Complete a chunked upload and persist the file to disk."""
    data = request.get_json()
    filename = data.get("filename")
    auto_segmentation = data.get("auto_segmentation", False)
    if not filename:
        return jsonify({"message": "Missing filename"}), 400
    chunks = chunk_storage.get(filename)
    if not chunks or any(chunk is None for chunk in chunks):
        return jsonify({"message": "Incomplete upload"}), 400
    combined = b"".join(chunks)
    file_path = os.path.join(UPLOAD_FOLDER, filename)
    with open(file_path, "wb") as f:
        f.write(combined)
    file_size = len(combined)
    project = {
        "key": str(uuid.uuid4()),
        "name": filename.rsplit(".", 1)[0] if "." in filename else filename,
        "file_name": filename,
        "uploaded": utc_now_iso(),
        "last_opened": None,
        "duration": 120.0,
        "fps": 30.0,
        "file_size": file_size,
        "segment_count": 0,
        "languages": ["en"],
        "thumbnail_url": None,
        "segmentation_done": auto_segmentation,
        "segmentation_progress": 100 if auto_segmentation else 0,
    }
    videos.append(project)
    del chunk_storage[filename]
    return jsonify({"message": "Upload finished", "project": project}), 200


# ─── Job endpoints ──────────────────────────────────────────────────────
@app.route("/start_job/<video_key>", methods=["POST"])
def start_job(video_key):
    """Start a background transcription job for the given video."""
    data = request.get_json()
    job_id = str(uuid.uuid4())
    job = {
        "id": job_id,
        "video_key": video_key,
        "status": "processing",
        "progress": 0.0,
        "transcript": None,
        "segments": None,
        "created_at": utc_now_iso(),
        "config": data,
    }
    jobs[job_id] = job
    threading.Thread(target=process_job, args=(job_id,), daemon=True).start()
    return jsonify({"job_id": job_id, "status": "processing"}), 200


@app.route("/job_status/<job_id>", methods=["GET"])
def job_status(job_id):
    """Return the current status of a transcription job."""
    job = jobs.get(job_id)
    if not job:
        return jsonify({"error": "Job not found"}), 404
    return (
        jsonify({
            "status": job["status"],
            "progress": job["progress"],
            "transcript": job.get("transcript"),
            "segments": job.get("segments"),
        }),
        200,
    )


# ─── Session output endpoints ──────────────────────────────────────────
@app.route("/session_output/<session_id>", methods=["GET"])
def get_session_output(session_id):
    """Get the session output as a JSON response with file URLs."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    token = request.headers.get("Authorization", "").replace("Bearer ", "")
    if not token:
        token = request.cookies.get("_forward_auth", "")

    files = []
    if os.path.exists(session_dir):
        for file in os.listdir(session_dir):
            file_path = os.path.join(session_dir, file)
            if os.path.isfile(file_path) and os.path.getsize(file_path) > 0:
                files.append({
                    "name": file,
                    "size": os.path.getsize(file_path),
                    "url": f"/session_file/{session_id}/{file}",
                })
        if files:
            return (
                jsonify({
                    "session_id": session_id,
                    "files": files,
                    "total_files": len(files),
                    "session_url": f"{INTERNAL_SERVER_URL}/archivesession/{session_id}",
                    "status": "ready",
                    "cached": True,
                }),
                200,
            )

    if token:
        logging.info("Downloading session %s from internal server", session_id)
        download_session_files(session_id, token)
        if os.path.exists(session_dir):
            for file in os.listdir(session_dir):
                file_path = os.path.join(session_dir, file)
                if os.path.isfile(file_path) and os.path.getsize(file_path) > 0:
                    files.append({
                        "name": file,
                        "size": os.path.getsize(file_path),
                        "url": f"/session_file/{session_id}/{file}",
                    })

    status = "ready" if files else "processing"
    return (
        jsonify({
            "session_id": session_id,
            "files": files,
            "total_files": len(files),
            "session_url": f"{INTERNAL_SERVER_URL}/archivesession/{session_id}",
            "status": status,
        }),
        200,
    )


@app.route("/session_file/<session_id>/<filename>", methods=["GET"])
def get_session_file(session_id, filename):
    """Download a specific file from the session."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    file_path = os.path.join(session_dir, filename)
    if not os.path.exists(file_path):
        return jsonify({"error": "File not found"}), 404
    return send_file(file_path, as_attachment=True)


@app.route("/session_zip/<session_id>", methods=["GET"])
def download_session_zip(session_id):
    """Download all session files as a ZIP archive."""
    session_dir = os.path.join(SESSION_FOLDER, session_id)
    if not os.path.exists(session_dir):
        return jsonify({"error": "Session not found"}), 404
    zip_path = os.path.join(tempfile.gettempdir(), f"session_{session_id}.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
        for root, _, files in os.walk(session_dir):
            for file in files:
                file_path = os.path.join(root, file)
                zipf.write(file_path, os.path.relpath(file_path, session_dir))
    return send_file(
        zip_path,
        as_attachment=True,
        download_name=f"session_{session_id}.zip",
        mimetype="application/zip",
    )

# ─── Upload endpoint ────────────────────────────────────────────────────
@app.route("/upload", methods=["POST", "OPTIONS"])
def upload_lecture():
    """Upload a video file to the internal server using requests."""
    if request.method == "OPTIONS":
        response = jsonify({"message": "OK"})
        response.headers.add("Access-Control-Allow-Origin", "*")
        response.headers.add("Access-Control-Allow-Headers", "Content-Type,Authorization")
        response.headers.add("Access-Control-Allow-Methods", "GET,POST,OPTIONS")
        return response, 200

    token = request.form.get("token", "")
    if not token:
        return jsonify({"error": "Missing token"}), 400
    if "videofile" not in request.files:
        return jsonify({"error": "No video file provided"}), 400

    file_storage = request.files["videofile"]
    if file_storage.filename == "":
        return jsonify({"error": "Empty filename"}), 400

    session_name = request.form.get("name", file_storage.filename)
    file_storage.seek(0)

    # ─── 1. SAVE LOCAL COPY ──────────────────────────────────────────
    local_filename = f"{uuid.uuid4()}_{file_storage.filename}"
    local_path = os.path.join(UPLOAD_FOLDER, local_filename)
    file_storage.save(local_path)
    file_size = os.path.getsize(local_path)
    file_storage.seek(0)
    logging.info("Saved local copy: %s (%d bytes)", local_filename, file_size)

    # ─── 2. CREATE PROJECT ENTRY ─────────────────────────────────────
    video_key = str(uuid.uuid4())
    project = {
        "key": video_key,
        "name": session_name,
        "file_name": local_filename,
        "uploaded": utc_now_iso(),
        "last_opened": None,
        "duration": 120.0,
        "fps": 30.0,
        "file_size": file_size,
        "segment_count": 0,
        "languages": request.form.getlist("language") or ["en"],
        "thumbnail_url": None,
        "segmentation_done": False,
        "segmentation_progress": 0,
    }
    videos.append(project)

    # ─── 3. BUILD DATA DICT ──────────────────────────────────────────
    data = {}
    for key in request.form.keys():
        if key == "token":
            continue
        values = request.form.getlist(key)
        data[key] = values[0] if len(values) == 1 else values
    if "path" not in data:
        data["path"] = "/home/admin@example.com"

    # ─── 4. BUILD FILES DICT ─────────────────────────────────────────
    files = {}
    if "videofile" in request.files:
        file_obj = request.files["videofile"]
        if file_obj.filename:
            # Read the file content to send
            file_obj.seek(0)
            file_content = file_obj.read()
            files["videofile"] = (file_obj.filename, file_content, file_obj.content_type)

    # ─── 5. SETUP HEADERS AND COOKIES ────────────────────────────────
    headers = {
        "X-Forward-Auth": token,
        "Authorization": f"Bearer {token}",
        "User-Agent": "Mozilla/5.0 (compatible; LT-Uploader/1.0)",
    }
    cookies = {"_forward_auth": token}

    # ─── 6. SEND TO INTERNAL SERVER ──────────────────────────────────
    try:
        logging.info("Uploading to internal server: %s", TARGET_URL)
        logging.info("Data keys: %s", list(data.keys()))
        logging.info("File: %s (%d bytes)", file_obj.filename if file_obj else 'None',
                     len(file_content) if 'file_content' in locals() else 0)

        resp = requests.post(
            TARGET_URL,
            data=data,
            files=files,
            headers=headers,
            cookies=cookies,
            timeout=(30, 3600),  # Extended timeout for large files
            verify=False,
            allow_redirects=True,
        )

        logging.info("Response status: %s", resp.status_code)
        logging.info("Response URL: %s", resp.url)

        final_url = resp.url
        session_id = None

        # Extract session ID from redirect URL
        if "/archivesession/" in final_url:
            session_id = final_url.split("/archivesession/")[-1].split("/")[0]
            logging.info("Extracted session ID from URL: %s", session_id)
        elif "/session/" in final_url:
            session_id = final_url.split("/session/")[-1].split("/")[0]
            logging.info("Extracted session ID from URL: %s", session_id)

        # If not found, build it from form data (fallback)
        if not session_id and session_name:
            user_email = data.get("path", "/home/admin@example.com").strip("/").split("/")[-1]
            path = f"/home/{user_email}/{session_name}"
            session_id = base64.b64encode(path.encode()).decode()
            logging.info("Generated session ID: %s", session_id)

        content = resp.text

        # ─── 7. UPDATE PROJECT WITH SESSION INFO ──────────────────────
        if session_id:
            project["session_id"] = session_id
            project["session_url"] = f"{BASE_URL}/archivesession/{session_id}"
            sessions[session_id] = {
                "id": session_id,
                "name": session_name,
                "video_key": video_key,
                "created_at": utc_now_iso(),
                "url": f"{BASE_URL}/archivesession/{session_id}",
            }
            logging.info("Session created: %s", session_id)

            # Start background job
            job = {
                "id": session_id,
                "video_key": video_key,
                "status": "processing",
                "progress": 0.0,
                "transcript": None,
                "segments": None,
                "created_at": utc_now_iso(),
                "config": dict(request.form),
            }
            jobs[session_id] = job
            threading.Thread(target=process_job, args=(session_id,), daemon=True).start()

        # ─── 8. RETURN RESPONSE ──────────────────────────────────────
        try:
            response_data = json.loads(content)
            if session_id:
                response_data.update({
                    "session_id": session_id,
                    "video_key": video_key,
                    "session_url": f"{BASE_URL}/archivesession/{session_id}",
                    "output_url": f"/session_output/{session_id}",
                    "download_url": f"/session_zip/{session_id}",
                })
            return jsonify(response_data), resp.status_code
        except json.JSONDecodeError:
            if session_id:
                return jsonify({
                    "status": "success",
                    "session_id": session_id,
                    "video_key": video_key,
                    "session_url": f"{BASE_URL}/archivesession/{session_id}",
                    "output_url": f"/session_output/{session_id}",
                    "download_url": f"/session_zip/{session_id}",
                    "message": "Upload successful!",
                    "response": content[:500]  # Include first 500 chars for debugging
                }), resp.status_code
            # If no session ID, return the raw response for debugging
            return jsonify({
                "status": "error",
                "message": "No session ID received",
                "response": content[:1000],
                "status_code": resp.status_code,
                "url": resp.url
            }), 500

    except requests.exceptions.Timeout:
        logging.error("Request timeout")
        return jsonify({"error": "Request timeout - file may be too large"}), 504
    except requests.exceptions.RequestException as e:
        logging.error("Request error: %s", str(e))
        return jsonify({"error": f"Request failed: {str(e)}"}), 500
    except OSError as e:
        logging.error("Upload error: %s", str(e), exc_info=True)
        return jsonify({"error": f"Upload failed: {str(e)}"}), 500

# ─── Proxy endpoints ────────────────────────────────────────────────────
@app.route("/check-session", methods=["GET"])
def check_session():
    """Forward a GET request to check if the session is authenticated."""
    headers = {}
    auth = request.headers.get("Authorization")
    if auth:
        headers["Authorization"] = auth
    forwarded_user = request.headers.get("X-Forwarded-User")
    if forwarded_user:
        headers["X-Forwarded-User"] = forwarded_user
    try:
        resp = requests.get(
            INTERNAL_SERVER_URL,
            headers=headers,
            allow_redirects=False,
            timeout=10,
            verify=False,
        )
        final_url = resp.url if hasattr(resp, "url") else INTERNAL_SERVER_URL
        is_login_page = resp.status_code == 200 and (
            "Log in to dex" in resp.text or "dex-container" in resp.text
        )
        authenticated = not (
            "dex" in final_url or resp.status_code == 302 or is_login_page
        )
        return jsonify({"authenticated": authenticated}), 200
    except requests.exceptions.RequestException:
        return jsonify({"authenticated": False, "error": "Request failed"}), 200


@app.route("/dex/token", methods=["POST"])
def dex_token():
    """Forward token exchange to the internal server's /dex/token endpoint."""
    try:
        headers = {k: v for k, v in request.headers if k.lower() != "host"}
        resp = requests.post(
            f"{INTERNAL_SERVER_URL}/dex/token",
            data=request.get_data(),
            headers=headers,
            allow_redirects=False,
            timeout=30,
            verify=False,
        )
        return (resp.content, resp.status_code, resp.headers.items())
    except requests.exceptions.RequestException as e:
        return jsonify({"error": f"Proxy error: {str(e)}"}), 500


@app.route("/dex/userinfo", methods=["GET"])
def dex_userinfo():
    """Forward userinfo request to the internal server's /dex/userinfo endpoint."""
    try:
        headers = {k: v for k, v in request.headers if k.lower() != "host"}
        resp = requests.get(
            f"{INTERNAL_SERVER_URL}/dex/userinfo",
            headers=headers,
            allow_redirects=False,
            timeout=30,
            verify=False,
        )
        return (resp.content, resp.status_code, resp.headers.items())
    except requests.exceptions.RequestException as e:
        return jsonify({"error": f"Proxy error: {str(e)}"}), 500


# ─── Debug endpoints ────────────────────────────────────────────────────
@app.route("/debug-videos", methods=["GET"])
def debug_videos():
    """Debug endpoint: return all video metadata."""
    return jsonify({"count": len(videos), "projects": videos}), 200


@app.route("/debug-jobs", methods=["GET"])
def debug_jobs():
    """Debug endpoint: return all jobs."""
    return jsonify({"count": len(jobs), "jobs": jobs}), 200


@app.route("/clear-videos", methods=["POST"])
def clear_videos():
    """Clear all uploaded videos (except the dummy one)."""
    for video in videos:
        if video.get("file_name") and video["file_name"] != "sample.mp4":
            file_path = os.path.join(UPLOAD_FOLDER, video["file_name"])
            if os.path.exists(file_path):
                os.remove(file_path)
    videos.clear()
    videos.append(dummy_project)
    chunk_storage.clear()
    jobs.clear()
    return jsonify({"message": "Cleared"}), 200


# ─── Main ──────────────────────────────────────────────────────────────
if __name__ == "__main__":
    try:
        import urllib3
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
    except ImportError:
        pass
    logging.info("Starting merged server on http://localhost:5000")
    app.run(host="0.0.0.0", port=5000, debug=True)
